//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LicensingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LicensingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LicensingResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a free version of {0}. Go {1}here{2} to see additional details..
        /// </summary>
        internal static string freeLicenseWarning {
            get {
                return ResourceManager.GetString("freeLicenseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, the license in your system is invalid. Contact your system administrator..
        /// </summary>
        internal static string invalidLicenseWarning {
            get {
                return ResourceManager.GetString("invalidLicenseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, you don’t have a license for {0}. Go {1}here{2} to purchase the full version and enable {3} .
        /// </summary>
        internal static string noLicenseWarning {
            get {
                return ResourceManager.GetString("noLicenseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a paid version of {0}. Go {1}here {2} to see additional details.
        /// </summary>
        internal static string paidLicenseMessage {
            get {
                return ResourceManager.GetString("paidLicenseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, there is no more time left in this trial. Go {0}here{1} to purchase the full version of this app and return to full functionality..
        /// </summary>
        internal static string trialExpiredWarning {
            get {
                return ResourceManager.GetString("trialExpiredWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a trial version of {0} and you have {1} remaining days. Go {2}here{3} to purchase the full version and unlock {4}.
        /// </summary>
        internal static string trialLimitedLicenseWarning {
            get {
                return ResourceManager.GetString("trialLimitedLicenseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a trial version of {0}. Go {1}here{2} to purchase the full version and unlock {3}.
        /// </summary>
        internal static string trialUnlimitedLicenseWarning {
            get {
                return ResourceManager.GetString("trialUnlimitedLicenseWarning", resourceCulture);
            }
        }
    }
}
