// Package.idl : IDL source for Package.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (Package.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
midl_pragma warning (disable : 2015)
import "vsshell.idl";
midl_pragma warning (default : 2015)

//standard dispids
#define DISPID_Name                     (-800)
#define DISPID_Delete                   (-801)
#define DISPID_Object                   (-802)
#define DISPID_Parent                   (-803)
#define DISPID_NewEnum					(-4)
#define DISPID_Value					(0)

[
	uuid(46ad5c8c-ba7c-49a4-9028-c8f7a552089d),
	version(1.0),
	helpstring("Package 1.0 Type Library")
]
library PackageLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");


	[
		uuid(cc69a0bd-0289-4a6e-9c20-96a186f7242a),
		helpstring("VSSDK Package.Reference Sample (C++)")
	]
	coclass PackagePackage
	{
		[default] interface IVsPackage;
	};
};
