//// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
//// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
//// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
//// PARTICULAR PURPOSE.
////
//// Copyright (c) Microsoft Corporation. All rights reserved.

import "oaidl.idl";
import "Inspectable.idl";
import "Windows.Foundation.idl";
import "uiautomationcore.idl";
#include <sdkddkver.h>

namespace UiaCoreWindowProvider
{
    // A TriColorValue for the TriColorValue control
    [v1_enum, version(NTDDI_WIN8)]
    typedef enum TriColorValue
    {
        Red,
        Yellow,
        Green
    } TriColorValue;

    // Internal interface for the TriColor control
    [version(NTDDI_WIN8), uuid(89AC8333-DD78-4C59-82C8-2143EF293C40)]
    interface ITriColorControlInternal : IInspectable{
        [propput]
        HRESULT ControlValue([in] TriColorValue value);
        [propget]
        HRESULT ControlValue([out, retval] TriColorValue * pvalue);
        [propget]
        HRESULT HasFocus([out, retval] VARIANT_BOOL * hasFocus);
        [propget]
        HRESULT ControlRect([out, retval] Windows.Foundation.Rect * prc);

        HRESULT RectFromValue([in] TriColorValue value, [out, retval] Windows.Foundation.Rect * prc);
        HRESULT ValueFromPoint([in] Windows.Foundation.Point pt, [out, retval] TriColorValue *value);
        HRESULT GetAppWindowProvider([out, retval] IInspectable ** provider);
        HRESULT GetTriColorControlProvider([out, retval] IInspectable ** provider);
        HRESULT GetTriColorFragmentProvider([in] TriColorValue value, [out, retval] IInspectable ** provider);
    };

    // Interface for a UIA provider that can be
    // initialized to a CoreWindow and also disconnected.
    [version(NTDDI_WIN8), uuid(0DC8AB6E-FF48-449C-9CF4-E321C4C166A2)]
    interface IDisconnectableProvider : IInspectable{
        HRESULT Disconnect();
    };

    // Initialization interface for the app window provider
    [version(NTDDI_WIN8), uuid(D722FFD7-484F-451E-B69C-5C88274B3062)]
    interface IAppWindowProvider : IInspectable{
        HRESULT Initialize
            ([in] ITriColorControlInternal* pControl, 
             [in] IInspectable* pWindow);
    };

    // Initialization interface for the control provider
    [version(NTDDI_WIN8), uuid(0A59600E-8B52-4E52-8949-81781B4C7D92)]
    interface ITriColorControlProvider : IInspectable{
        HRESULT Initialize
            ([in] ITriColorControlInternal* pControl);
    };

    // Initialization interface for the fragment provider
    [version(NTDDI_WIN8), uuid(4F925A18-4476-43DE-AC3C-0AB21386EF1A)]
    interface ITriColorFragmentProvider : IInspectable{
        HRESULT Initialize
            ([in] ITriColorControlInternal* pControl, 
             [in] TriColorValue value);
    };

    [version(NTDDI_WIN8), activatable(NTDDI_WIN8)]
    runtimeclass AppWindowProvider
    {
        [default] interface IAppWindowProvider;
    }

    [version(NTDDI_WIN8), activatable(NTDDI_WIN8)]
    runtimeclass TriColorControlProvider
    {
        [default] interface ITriColorControlProvider;
    }

    [version(NTDDI_WIN8), activatable(NTDDI_WIN8)]
    runtimeclass TriColorFragmentProvider
    {
        [default] interface ITriColorFragmentProvider;
    }
}