//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40818.0
// 
namespace SEARCH_FromSilverlight.SharePointSearchService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.com/webservices/OfficeServer/QueryService", ConfigurationName="SharePointSearchService.QueryServiceSoap")]
    public interface QueryServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:Microsoft.Search/Query", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginQuery(SEARCH_FromSilverlight.SharePointSearchService.QueryRequest request, System.AsyncCallback callback, object asyncState);
        
        SEARCH_FromSilverlight.SharePointSearchService.QueryResponse EndQuery(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://microsoft.com/webservices/OfficeServer/QueryService/QueryEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginQueryEx(string queryXml, System.AsyncCallback callback, object asyncState);
        
        SEARCH_FromSilverlight.SharePointSearchService.ArrayOfXElement EndQueryEx(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:Microsoft.Search/Registration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginRegistration(SEARCH_FromSilverlight.SharePointSearchService.RegistrationRequest request, System.AsyncCallback callback, object asyncState);
        
        SEARCH_FromSilverlight.SharePointSearchService.RegistrationResponse EndRegistration(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:Microsoft.Search/Status", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginStatus(SEARCH_FromSilverlight.SharePointSearchService.StatusRequest request, System.AsyncCallback callback, object asyncState);
        
        SEARCH_FromSilverlight.SharePointSearchService.StatusResponse EndStatus(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://microsoft.com/webservices/OfficeServer/QueryService/GetPortalSearchInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetPortalSearchInfo(System.AsyncCallback callback, object asyncState);
        
        string EndGetPortalSearchInfo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://microsoft.com/webservices/OfficeServer/QueryService/GetSearchMetadata", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetSearchMetadata(System.AsyncCallback callback, object asyncState);
        
        SEARCH_FromSilverlight.SharePointSearchService.ArrayOfXElement EndGetSearchMetadata(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:Microsoft.Search/RecordClick", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginRecordClick(SEARCH_FromSilverlight.SharePointSearchService.RecordClickRequest request, System.AsyncCallback callback, object asyncState);
        
        SEARCH_FromSilverlight.SharePointSearchService.RecordClickResponse EndRecordClick(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://microsoft.com/webservices/OfficeServer/QueryService/GetQuerySuggestions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetQuerySuggestions(string queryXml, System.AsyncCallback callback, object asyncState);
        
        string[] EndGetQuerySuggestions(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Query", WrapperNamespace="urn:Microsoft.Search", IsWrapped=true)]
    public partial class QueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microsoft.Search", Order=0)]
        public string queryXml;
        
        public QueryRequest() {
        }
        
        public QueryRequest(string queryXml) {
            this.queryXml = queryXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryResponse", WrapperNamespace="urn:Microsoft.Search", IsWrapped=true)]
    public partial class QueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microsoft.Search", Order=0)]
        public string QueryResult;
        
        public QueryResponse() {
        }
        
        public QueryResponse(string QueryResult) {
            this.QueryResult = QueryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Registration", WrapperNamespace="urn:Microsoft.Search", IsWrapped=true)]
    public partial class RegistrationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microsoft.Search", Order=0)]
        public string registrationXml;
        
        public RegistrationRequest() {
        }
        
        public RegistrationRequest(string registrationXml) {
            this.registrationXml = registrationXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrationResponse", WrapperNamespace="urn:Microsoft.Search", IsWrapped=true)]
    public partial class RegistrationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microsoft.Search", Order=0)]
        public string RegistrationResult;
        
        public RegistrationResponse() {
        }
        
        public RegistrationResponse(string RegistrationResult) {
            this.RegistrationResult = RegistrationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Status", WrapperNamespace="urn:Microsoft.Search", IsWrapped=true)]
    public partial class StatusRequest {
        
        public StatusRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StatusResponse", WrapperNamespace="urn:Microsoft.Search", IsWrapped=true)]
    public partial class StatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microsoft.Search", Order=0)]
        public string StatusResult;
        
        public StatusResponse() {
        }
        
        public StatusResponse(string StatusResult) {
            this.StatusResult = StatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecordClick", WrapperNamespace="urn:Microsoft.Search", IsWrapped=true)]
    public partial class RecordClickRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microsoft.Search", Order=0)]
        public string clickInfoXml;
        
        public RecordClickRequest() {
        }
        
        public RecordClickRequest(string clickInfoXml) {
            this.clickInfoXml = clickInfoXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecordClickResponse", WrapperNamespace="urn:Microsoft.Search", IsWrapped=true)]
    public partial class RecordClickResponse {
        
        public RecordClickResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QueryServiceSoapChannel : SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public QueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public QueryExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SEARCH_FromSilverlight.SharePointSearchService.ArrayOfXElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SEARCH_FromSilverlight.SharePointSearchService.ArrayOfXElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RegistrationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public StatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPortalSearchInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPortalSearchInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSearchMetadataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSearchMetadataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SEARCH_FromSilverlight.SharePointSearchService.ArrayOfXElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SEARCH_FromSilverlight.SharePointSearchService.ArrayOfXElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetQuerySuggestionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetQuerySuggestionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryServiceSoapClient : System.ServiceModel.ClientBase<SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap>, SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap {
        
        private BeginOperationDelegate onBeginQueryDelegate;
        
        private EndOperationDelegate onEndQueryDelegate;
        
        private System.Threading.SendOrPostCallback onQueryCompletedDelegate;
        
        private BeginOperationDelegate onBeginQueryExDelegate;
        
        private EndOperationDelegate onEndQueryExDelegate;
        
        private System.Threading.SendOrPostCallback onQueryExCompletedDelegate;
        
        private BeginOperationDelegate onBeginRegistrationDelegate;
        
        private EndOperationDelegate onEndRegistrationDelegate;
        
        private System.Threading.SendOrPostCallback onRegistrationCompletedDelegate;
        
        private BeginOperationDelegate onBeginStatusDelegate;
        
        private EndOperationDelegate onEndStatusDelegate;
        
        private System.Threading.SendOrPostCallback onStatusCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetPortalSearchInfoDelegate;
        
        private EndOperationDelegate onEndGetPortalSearchInfoDelegate;
        
        private System.Threading.SendOrPostCallback onGetPortalSearchInfoCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSearchMetadataDelegate;
        
        private EndOperationDelegate onEndGetSearchMetadataDelegate;
        
        private System.Threading.SendOrPostCallback onGetSearchMetadataCompletedDelegate;
        
        private BeginOperationDelegate onBeginRecordClickDelegate;
        
        private EndOperationDelegate onEndRecordClickDelegate;
        
        private System.Threading.SendOrPostCallback onRecordClickCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetQuerySuggestionsDelegate;
        
        private EndOperationDelegate onEndGetQuerySuggestionsDelegate;
        
        private System.Threading.SendOrPostCallback onGetQuerySuggestionsCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public QueryServiceSoapClient() {
        }
        
        public QueryServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueryServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<QueryCompletedEventArgs> QueryCompleted;
        
        public event System.EventHandler<QueryExCompletedEventArgs> QueryExCompleted;
        
        public event System.EventHandler<RegistrationCompletedEventArgs> RegistrationCompleted;
        
        public event System.EventHandler<StatusCompletedEventArgs> StatusCompleted;
        
        public event System.EventHandler<GetPortalSearchInfoCompletedEventArgs> GetPortalSearchInfoCompleted;
        
        public event System.EventHandler<GetSearchMetadataCompletedEventArgs> GetSearchMetadataCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> RecordClickCompleted;
        
        public event System.EventHandler<GetQuerySuggestionsCompletedEventArgs> GetQuerySuggestionsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap.BeginQuery(SEARCH_FromSilverlight.SharePointSearchService.QueryRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginQuery(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginQuery(string queryXml, System.AsyncCallback callback, object asyncState) {
            SEARCH_FromSilverlight.SharePointSearchService.QueryRequest inValue = new SEARCH_FromSilverlight.SharePointSearchService.QueryRequest();
            inValue.queryXml = queryXml;
            return ((SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap)(this)).BeginQuery(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SEARCH_FromSilverlight.SharePointSearchService.QueryResponse SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap.EndQuery(System.IAsyncResult result) {
            return base.Channel.EndQuery(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndQuery(System.IAsyncResult result) {
            SEARCH_FromSilverlight.SharePointSearchService.QueryResponse retVal = ((SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap)(this)).EndQuery(result);
            return retVal.QueryResult;
        }
        
        private System.IAsyncResult OnBeginQuery(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string queryXml = ((string)(inValues[0]));
            return this.BeginQuery(queryXml, callback, asyncState);
        }
        
        private object[] OnEndQuery(System.IAsyncResult result) {
            string retVal = this.EndQuery(result);
            return new object[] {
                    retVal};
        }
        
        private void OnQueryCompleted(object state) {
            if ((this.QueryCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.QueryCompleted(this, new QueryCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void QueryAsync(string queryXml) {
            this.QueryAsync(queryXml, null);
        }
        
        public void QueryAsync(string queryXml, object userState) {
            if ((this.onBeginQueryDelegate == null)) {
                this.onBeginQueryDelegate = new BeginOperationDelegate(this.OnBeginQuery);
            }
            if ((this.onEndQueryDelegate == null)) {
                this.onEndQueryDelegate = new EndOperationDelegate(this.OnEndQuery);
            }
            if ((this.onQueryCompletedDelegate == null)) {
                this.onQueryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnQueryCompleted);
            }
            base.InvokeAsync(this.onBeginQueryDelegate, new object[] {
                        queryXml}, this.onEndQueryDelegate, this.onQueryCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap.BeginQueryEx(string queryXml, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginQueryEx(queryXml, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SEARCH_FromSilverlight.SharePointSearchService.ArrayOfXElement SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap.EndQueryEx(System.IAsyncResult result) {
            return base.Channel.EndQueryEx(result);
        }
        
        private System.IAsyncResult OnBeginQueryEx(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string queryXml = ((string)(inValues[0]));
            return ((SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap)(this)).BeginQueryEx(queryXml, callback, asyncState);
        }
        
        private object[] OnEndQueryEx(System.IAsyncResult result) {
            SEARCH_FromSilverlight.SharePointSearchService.ArrayOfXElement retVal = ((SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap)(this)).EndQueryEx(result);
            return new object[] {
                    retVal};
        }
        
        private void OnQueryExCompleted(object state) {
            if ((this.QueryExCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.QueryExCompleted(this, new QueryExCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void QueryExAsync(string queryXml) {
            this.QueryExAsync(queryXml, null);
        }
        
        public void QueryExAsync(string queryXml, object userState) {
            if ((this.onBeginQueryExDelegate == null)) {
                this.onBeginQueryExDelegate = new BeginOperationDelegate(this.OnBeginQueryEx);
            }
            if ((this.onEndQueryExDelegate == null)) {
                this.onEndQueryExDelegate = new EndOperationDelegate(this.OnEndQueryEx);
            }
            if ((this.onQueryExCompletedDelegate == null)) {
                this.onQueryExCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnQueryExCompleted);
            }
            base.InvokeAsync(this.onBeginQueryExDelegate, new object[] {
                        queryXml}, this.onEndQueryExDelegate, this.onQueryExCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap.BeginRegistration(SEARCH_FromSilverlight.SharePointSearchService.RegistrationRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRegistration(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginRegistration(string registrationXml, System.AsyncCallback callback, object asyncState) {
            SEARCH_FromSilverlight.SharePointSearchService.RegistrationRequest inValue = new SEARCH_FromSilverlight.SharePointSearchService.RegistrationRequest();
            inValue.registrationXml = registrationXml;
            return ((SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap)(this)).BeginRegistration(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SEARCH_FromSilverlight.SharePointSearchService.RegistrationResponse SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap.EndRegistration(System.IAsyncResult result) {
            return base.Channel.EndRegistration(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndRegistration(System.IAsyncResult result) {
            SEARCH_FromSilverlight.SharePointSearchService.RegistrationResponse retVal = ((SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap)(this)).EndRegistration(result);
            return retVal.RegistrationResult;
        }
        
        private System.IAsyncResult OnBeginRegistration(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string registrationXml = ((string)(inValues[0]));
            return this.BeginRegistration(registrationXml, callback, asyncState);
        }
        
        private object[] OnEndRegistration(System.IAsyncResult result) {
            string retVal = this.EndRegistration(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRegistrationCompleted(object state) {
            if ((this.RegistrationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RegistrationCompleted(this, new RegistrationCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RegistrationAsync(string registrationXml) {
            this.RegistrationAsync(registrationXml, null);
        }
        
        public void RegistrationAsync(string registrationXml, object userState) {
            if ((this.onBeginRegistrationDelegate == null)) {
                this.onBeginRegistrationDelegate = new BeginOperationDelegate(this.OnBeginRegistration);
            }
            if ((this.onEndRegistrationDelegate == null)) {
                this.onEndRegistrationDelegate = new EndOperationDelegate(this.OnEndRegistration);
            }
            if ((this.onRegistrationCompletedDelegate == null)) {
                this.onRegistrationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRegistrationCompleted);
            }
            base.InvokeAsync(this.onBeginRegistrationDelegate, new object[] {
                        registrationXml}, this.onEndRegistrationDelegate, this.onRegistrationCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap.BeginStatus(SEARCH_FromSilverlight.SharePointSearchService.StatusRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginStatus(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginStatus(System.AsyncCallback callback, object asyncState) {
            SEARCH_FromSilverlight.SharePointSearchService.StatusRequest inValue = new SEARCH_FromSilverlight.SharePointSearchService.StatusRequest();
            return ((SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap)(this)).BeginStatus(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SEARCH_FromSilverlight.SharePointSearchService.StatusResponse SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap.EndStatus(System.IAsyncResult result) {
            return base.Channel.EndStatus(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndStatus(System.IAsyncResult result) {
            SEARCH_FromSilverlight.SharePointSearchService.StatusResponse retVal = ((SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap)(this)).EndStatus(result);
            return retVal.StatusResult;
        }
        
        private System.IAsyncResult OnBeginStatus(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginStatus(callback, asyncState);
        }
        
        private object[] OnEndStatus(System.IAsyncResult result) {
            string retVal = this.EndStatus(result);
            return new object[] {
                    retVal};
        }
        
        private void OnStatusCompleted(object state) {
            if ((this.StatusCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.StatusCompleted(this, new StatusCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void StatusAsync() {
            this.StatusAsync(null);
        }
        
        public void StatusAsync(object userState) {
            if ((this.onBeginStatusDelegate == null)) {
                this.onBeginStatusDelegate = new BeginOperationDelegate(this.OnBeginStatus);
            }
            if ((this.onEndStatusDelegate == null)) {
                this.onEndStatusDelegate = new EndOperationDelegate(this.OnEndStatus);
            }
            if ((this.onStatusCompletedDelegate == null)) {
                this.onStatusCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnStatusCompleted);
            }
            base.InvokeAsync(this.onBeginStatusDelegate, null, this.onEndStatusDelegate, this.onStatusCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap.BeginGetPortalSearchInfo(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPortalSearchInfo(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap.EndGetPortalSearchInfo(System.IAsyncResult result) {
            return base.Channel.EndGetPortalSearchInfo(result);
        }
        
        private System.IAsyncResult OnBeginGetPortalSearchInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap)(this)).BeginGetPortalSearchInfo(callback, asyncState);
        }
        
        private object[] OnEndGetPortalSearchInfo(System.IAsyncResult result) {
            string retVal = ((SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap)(this)).EndGetPortalSearchInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPortalSearchInfoCompleted(object state) {
            if ((this.GetPortalSearchInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPortalSearchInfoCompleted(this, new GetPortalSearchInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPortalSearchInfoAsync() {
            this.GetPortalSearchInfoAsync(null);
        }
        
        public void GetPortalSearchInfoAsync(object userState) {
            if ((this.onBeginGetPortalSearchInfoDelegate == null)) {
                this.onBeginGetPortalSearchInfoDelegate = new BeginOperationDelegate(this.OnBeginGetPortalSearchInfo);
            }
            if ((this.onEndGetPortalSearchInfoDelegate == null)) {
                this.onEndGetPortalSearchInfoDelegate = new EndOperationDelegate(this.OnEndGetPortalSearchInfo);
            }
            if ((this.onGetPortalSearchInfoCompletedDelegate == null)) {
                this.onGetPortalSearchInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPortalSearchInfoCompleted);
            }
            base.InvokeAsync(this.onBeginGetPortalSearchInfoDelegate, null, this.onEndGetPortalSearchInfoDelegate, this.onGetPortalSearchInfoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap.BeginGetSearchMetadata(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSearchMetadata(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SEARCH_FromSilverlight.SharePointSearchService.ArrayOfXElement SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap.EndGetSearchMetadata(System.IAsyncResult result) {
            return base.Channel.EndGetSearchMetadata(result);
        }
        
        private System.IAsyncResult OnBeginGetSearchMetadata(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap)(this)).BeginGetSearchMetadata(callback, asyncState);
        }
        
        private object[] OnEndGetSearchMetadata(System.IAsyncResult result) {
            SEARCH_FromSilverlight.SharePointSearchService.ArrayOfXElement retVal = ((SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap)(this)).EndGetSearchMetadata(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSearchMetadataCompleted(object state) {
            if ((this.GetSearchMetadataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSearchMetadataCompleted(this, new GetSearchMetadataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSearchMetadataAsync() {
            this.GetSearchMetadataAsync(null);
        }
        
        public void GetSearchMetadataAsync(object userState) {
            if ((this.onBeginGetSearchMetadataDelegate == null)) {
                this.onBeginGetSearchMetadataDelegate = new BeginOperationDelegate(this.OnBeginGetSearchMetadata);
            }
            if ((this.onEndGetSearchMetadataDelegate == null)) {
                this.onEndGetSearchMetadataDelegate = new EndOperationDelegate(this.OnEndGetSearchMetadata);
            }
            if ((this.onGetSearchMetadataCompletedDelegate == null)) {
                this.onGetSearchMetadataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSearchMetadataCompleted);
            }
            base.InvokeAsync(this.onBeginGetSearchMetadataDelegate, null, this.onEndGetSearchMetadataDelegate, this.onGetSearchMetadataCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap.BeginRecordClick(SEARCH_FromSilverlight.SharePointSearchService.RecordClickRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRecordClick(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginRecordClick(string clickInfoXml, System.AsyncCallback callback, object asyncState) {
            SEARCH_FromSilverlight.SharePointSearchService.RecordClickRequest inValue = new SEARCH_FromSilverlight.SharePointSearchService.RecordClickRequest();
            inValue.clickInfoXml = clickInfoXml;
            return ((SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap)(this)).BeginRecordClick(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SEARCH_FromSilverlight.SharePointSearchService.RecordClickResponse SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap.EndRecordClick(System.IAsyncResult result) {
            return base.Channel.EndRecordClick(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private void EndRecordClick(System.IAsyncResult result) {
            SEARCH_FromSilverlight.SharePointSearchService.RecordClickResponse retVal = ((SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap)(this)).EndRecordClick(result);
        }
        
        private System.IAsyncResult OnBeginRecordClick(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string clickInfoXml = ((string)(inValues[0]));
            return this.BeginRecordClick(clickInfoXml, callback, asyncState);
        }
        
        private object[] OnEndRecordClick(System.IAsyncResult result) {
            this.EndRecordClick(result);
            return null;
        }
        
        private void OnRecordClickCompleted(object state) {
            if ((this.RecordClickCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RecordClickCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RecordClickAsync(string clickInfoXml) {
            this.RecordClickAsync(clickInfoXml, null);
        }
        
        public void RecordClickAsync(string clickInfoXml, object userState) {
            if ((this.onBeginRecordClickDelegate == null)) {
                this.onBeginRecordClickDelegate = new BeginOperationDelegate(this.OnBeginRecordClick);
            }
            if ((this.onEndRecordClickDelegate == null)) {
                this.onEndRecordClickDelegate = new EndOperationDelegate(this.OnEndRecordClick);
            }
            if ((this.onRecordClickCompletedDelegate == null)) {
                this.onRecordClickCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRecordClickCompleted);
            }
            base.InvokeAsync(this.onBeginRecordClickDelegate, new object[] {
                        clickInfoXml}, this.onEndRecordClickDelegate, this.onRecordClickCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap.BeginGetQuerySuggestions(string queryXml, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetQuerySuggestions(queryXml, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string[] SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap.EndGetQuerySuggestions(System.IAsyncResult result) {
            return base.Channel.EndGetQuerySuggestions(result);
        }
        
        private System.IAsyncResult OnBeginGetQuerySuggestions(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string queryXml = ((string)(inValues[0]));
            return ((SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap)(this)).BeginGetQuerySuggestions(queryXml, callback, asyncState);
        }
        
        private object[] OnEndGetQuerySuggestions(System.IAsyncResult result) {
            string[] retVal = ((SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap)(this)).EndGetQuerySuggestions(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetQuerySuggestionsCompleted(object state) {
            if ((this.GetQuerySuggestionsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetQuerySuggestionsCompleted(this, new GetQuerySuggestionsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetQuerySuggestionsAsync(string queryXml) {
            this.GetQuerySuggestionsAsync(queryXml, null);
        }
        
        public void GetQuerySuggestionsAsync(string queryXml, object userState) {
            if ((this.onBeginGetQuerySuggestionsDelegate == null)) {
                this.onBeginGetQuerySuggestionsDelegate = new BeginOperationDelegate(this.OnBeginGetQuerySuggestions);
            }
            if ((this.onEndGetQuerySuggestionsDelegate == null)) {
                this.onEndGetQuerySuggestionsDelegate = new EndOperationDelegate(this.OnEndGetQuerySuggestions);
            }
            if ((this.onGetQuerySuggestionsCompletedDelegate == null)) {
                this.onGetQuerySuggestionsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetQuerySuggestionsCompleted);
            }
            base.InvokeAsync(this.onBeginGetQuerySuggestionsDelegate, new object[] {
                        queryXml}, this.onEndGetQuerySuggestionsDelegate, this.onGetQuerySuggestionsCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap CreateChannel() {
            return new QueryServiceSoapClientChannel(this);
        }
        
        private class QueryServiceSoapClientChannel : ChannelBase<SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap>, SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap {
            
            public QueryServiceSoapClientChannel(System.ServiceModel.ClientBase<SEARCH_FromSilverlight.SharePointSearchService.QueryServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginQuery(SEARCH_FromSilverlight.SharePointSearchService.QueryRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Query", _args, callback, asyncState);
                return _result;
            }
            
            public SEARCH_FromSilverlight.SharePointSearchService.QueryResponse EndQuery(System.IAsyncResult result) {
                object[] _args = new object[0];
                SEARCH_FromSilverlight.SharePointSearchService.QueryResponse _result = ((SEARCH_FromSilverlight.SharePointSearchService.QueryResponse)(base.EndInvoke("Query", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginQueryEx(string queryXml, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = queryXml;
                System.IAsyncResult _result = base.BeginInvoke("QueryEx", _args, callback, asyncState);
                return _result;
            }
            
            public SEARCH_FromSilverlight.SharePointSearchService.ArrayOfXElement EndQueryEx(System.IAsyncResult result) {
                object[] _args = new object[0];
                SEARCH_FromSilverlight.SharePointSearchService.ArrayOfXElement _result = ((SEARCH_FromSilverlight.SharePointSearchService.ArrayOfXElement)(base.EndInvoke("QueryEx", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRegistration(SEARCH_FromSilverlight.SharePointSearchService.RegistrationRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Registration", _args, callback, asyncState);
                return _result;
            }
            
            public SEARCH_FromSilverlight.SharePointSearchService.RegistrationResponse EndRegistration(System.IAsyncResult result) {
                object[] _args = new object[0];
                SEARCH_FromSilverlight.SharePointSearchService.RegistrationResponse _result = ((SEARCH_FromSilverlight.SharePointSearchService.RegistrationResponse)(base.EndInvoke("Registration", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginStatus(SEARCH_FromSilverlight.SharePointSearchService.StatusRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Status", _args, callback, asyncState);
                return _result;
            }
            
            public SEARCH_FromSilverlight.SharePointSearchService.StatusResponse EndStatus(System.IAsyncResult result) {
                object[] _args = new object[0];
                SEARCH_FromSilverlight.SharePointSearchService.StatusResponse _result = ((SEARCH_FromSilverlight.SharePointSearchService.StatusResponse)(base.EndInvoke("Status", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetPortalSearchInfo(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetPortalSearchInfo", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetPortalSearchInfo(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetPortalSearchInfo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetSearchMetadata(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetSearchMetadata", _args, callback, asyncState);
                return _result;
            }
            
            public SEARCH_FromSilverlight.SharePointSearchService.ArrayOfXElement EndGetSearchMetadata(System.IAsyncResult result) {
                object[] _args = new object[0];
                SEARCH_FromSilverlight.SharePointSearchService.ArrayOfXElement _result = ((SEARCH_FromSilverlight.SharePointSearchService.ArrayOfXElement)(base.EndInvoke("GetSearchMetadata", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRecordClick(SEARCH_FromSilverlight.SharePointSearchService.RecordClickRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("RecordClick", _args, callback, asyncState);
                return _result;
            }
            
            public SEARCH_FromSilverlight.SharePointSearchService.RecordClickResponse EndRecordClick(System.IAsyncResult result) {
                object[] _args = new object[0];
                SEARCH_FromSilverlight.SharePointSearchService.RecordClickResponse _result = ((SEARCH_FromSilverlight.SharePointSearchService.RecordClickResponse)(base.EndInvoke("RecordClick", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetQuerySuggestions(string queryXml, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = queryXml;
                System.IAsyncResult _result = base.BeginInvoke("GetQuerySuggestions", _args, callback, asyncState);
                return _result;
            }
            
            public string[] EndGetQuerySuggestions(System.IAsyncResult result) {
                object[] _args = new object[0];
                string[] _result = ((string[])(base.EndInvoke("GetQuerySuggestions", _args, result)));
                return _result;
            }
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Silverlight.ServiceReference", "3.0.0.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement() {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes {
            get {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema() {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer) {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            ) {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader) {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            ) {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element)) {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else {
                    reader.Skip();
                }
            }
        }
    }
}
