/*++
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
//
// Copyright (c) Microsoft Corporation. All rights reserved
//
// Module:
    SensorsServiceDriver.idl
//      
//
// Description:
//  Sensors service driver

--*/

import "wudfddi.idl";

[
    uuid(cbb555e7-a07a-4fac-a32b-94428ce1c592),
    version(1.0),
    helpstring("Geolocation Sensor Driver Sample Type Library")
]
library SensorsGeolocationDriverSampleLib
{
    importlib("stdole2.tlb");
    [
        uuid(ceeb6d87-3f96-4cc8-9f46-369939171dc7),
        helpstring("SensorsGeolocationDriverSample Class")
    ]
    coclass SensorsGeolocationDriverSample
    {
        [default] interface IDriverEntry;
    };
};
