<?xml version="1.0" encoding="utf-8"?>
<Database Name="NORTHWIND" Class="NorthwindDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\SampleData\NORTHWIND.MDF;Integrated Security=True;User Instance=True" SettingsObjectName="SampleQueries.My.MySettings" SettingsPropertyName="NORTHWINDConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.String" DbType="NChar(5)" CanBeNull="true" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RequiredDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ShippedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ShipVia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Freight" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ShipName" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="ShipAddress" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="ShipCity" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="ShipRegion" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="ShipPostalCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ShipCountry" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Association Name="Order_Order_Detail" Member="Order_Details" OtherKey="OrderID" Type="Order_Detail" />
      <Association Name="Employee_Order" Member="Employee" ThisKey="EmployeeID" Type="Employee" IsForeignKey="true" />
      <Association Name="Customer_Order" Member="Customer" ThisKey="CustomerID" Type="Customer" IsForeignKey="true" />
      <Association Name="Shipper_Order" Member="Shipper" ThisKey="ShipVia" Type="Shipper" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="SupplierID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuantityPerUnit" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="UnitsInStock" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="UnitsOnOrder" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ReorderLevel" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Discontinued" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Product_Order_Detail" Member="Order_Details" OtherKey="ProductID" Type="Order_Detail" />
      <Association Name="Category_Product" Member="Category" ThisKey="CategoryID" Type="Category" IsForeignKey="true" />
      <Association Name="Supplier_Product" Member="Supplier" ThisKey="SupplierID" Type="Supplier" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CustomerCustomerDemo" Member="CustomerCustomerDemos">
    <Type Name="CustomerCustomerDemo">
      <Column Name="CustomerID" Type="System.String" DbType="NChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustomerTypeID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="CustomerDemographic_CustomerCustomerDemo" Member="CustomerDemographic" ThisKey="CustomerTypeID" Type="CustomerDemographic" IsForeignKey="true" />
      <Association Name="Customer_CustomerCustomerDemo" Member="Customer" ThisKey="CustomerID" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CustomerDemographics" Member="CustomerDemographics">
    <Type Name="CustomerDemographic">
      <Column Name="CustomerTypeID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustomerDesc" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="CustomerDemographic_CustomerCustomerDemo" Member="CustomerCustomerDemos" OtherKey="CustomerTypeID" Type="CustomerCustomerDemo" />
    </Type>
  </Table>
  <Table Name="dbo.Region" Member="Regions">
    <Type Name="Region">
      <Column Name="RegionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RegionDescription" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Region_Territory" Member="Territories" OtherKey="RegionID" Type="Territory" />
    </Type>
  </Table>
  <Table Name="dbo.Territories" Member="Territories">
    <Type Name="Territory">
      <Column Name="TerritoryID" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TerritoryDescription" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RegionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Territory_EmployeeTerritory" Member="EmployeeTerritories" OtherKey="TerritoryID" Type="EmployeeTerritory" />
      <Association Name="Region_Territory" Member="Region" ThisKey="RegionID" Type="Region" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EmployeeTerritories" Member="EmployeeTerritories">
    <Type Name="EmployeeTerritory">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TerritoryID" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Territory_EmployeeTerritory" Member="Territory" ThisKey="TerritoryID" Type="Territory" IsForeignKey="true" />
      <Association Name="Employee_EmployeeTerritory" Member="Employee" ThisKey="EmployeeID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TitleOfCourtesy" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HireDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="HomePhone" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="Extension" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="Photo" Type="System.Byte[]" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Notes" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ReportsTo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhotoPath" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Employee_Order" Member="Orders" OtherKey="EmployeeID" Type="Order" />
      <Association Name="Employee_EmployeeTerritory" Member="EmployeeTerritories" OtherKey="EmployeeID" Type="EmployeeTerritory" />
      <Association Name="Employee_Employee" Member="Employees" OtherKey="ReportsTo" Type="Employee" />
      <Association Name="Employee_Employee" Member="Employee" ThisKey="ReportsTo" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Category">
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Picture" Type="System.Byte[]" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Category_Product" Member="Products" OtherKey="CategoryID" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerID" Type="System.String" DbType="NChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="ContactName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ContactTitle" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Association Name="Customer_Order" Member="Orders" OtherKey="CustomerID" Type="Order" />
      <Association Name="Customer_CustomerCustomerDemo" Member="CustomerCustomerDemos" OtherKey="CustomerID" Type="CustomerCustomerDemo" />
    </Type>
  </Table>
  <Table Name="dbo.Shippers" Member="Shippers">
    <Type Name="Shipper">
      <Column Name="ShipperID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Association Name="Shipper_Order" Member="Orders" OtherKey="ShipVia" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.Suppliers" Member="Suppliers">
    <Type Name="Supplier">
      <Column Name="SupplierID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="ContactName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ContactTitle" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="HomePage" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Supplier_Product" Member="Products" OtherKey="SupplierID" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Contacts" Member="Contacts">
    <Type Name="Contact">
      <Column Name="ContactID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ContactType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="ContactName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ContactTitle" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="Extension" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="HomePage" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PhotoPath" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Photo" Type="System.Byte[]" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.[Quarterly Orders]" Member="Quarterly_Orders">
    <Type Name="Quarterly_Order">
      <Column Name="CustomerID" Type="System.String" DbType="NChar(5)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Invoices" Member="Invoices">
    <Type Name="Invoice">
      <Column Name="ShipName" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="ShipAddress" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="ShipCity" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="ShipRegion" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="ShipPostalCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ShipCountry" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="CustomerID" Type="System.String" DbType="NChar(5)" CanBeNull="true" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Salesperson" Type="System.String" DbType="NVarChar(31) NOT NULL" CanBeNull="false" />
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RequiredDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ShippedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ShipperName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="ExtendedPrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Freight" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Order Details]" Member="Order_Details">
    <Type Name="Order_Detail">
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Association Name="Order_Order_Detail" Member="Order" ThisKey="OrderID" Type="Order" IsForeignKey="true" />
      <Association Name="Product_Order_Detail" Member="Product" ThisKey="ProductID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.[Customers By City]" Method="Customers_By_City">
    <Parameter Name="@param1" Parameter="param1" Type="System.String" DbType="nvarchar" />
    <ElementType Name="Customers_By_City">
      <Column Name="CustomerID" Type="System.String" DbType="NChar(5) NOT NULL" IsReadOnly="true" CanBeNull="false" />
      <Column Name="ContactName" Type="System.String" DbType="NVarChar(30)" IsReadOnly="true" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(40) NOT NULL" IsReadOnly="true" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NVarChar(15)" IsReadOnly="true" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ProductsUnderThisUnitPrice" Method="ProductsUnderThisUnitPrice" IsComposable="true">
    <Parameter Name="@price" Parameter="price" Type="System.Decimal" DbType="money" />
    <ElementType Name="ProductsUnderThisUnitPrice">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" IsReadOnly="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(40) NOT NULL" IsReadOnly="true" CanBeNull="false" />
      <Column Name="SupplierID" Type="System.Int32" DbType="Int" IsReadOnly="true" CanBeNull="true" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int" IsReadOnly="true" CanBeNull="true" />
      <Column Name="QuantityPerUnit" Type="System.String" DbType="NVarChar(20)" IsReadOnly="true" CanBeNull="true" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Money" IsReadOnly="true" CanBeNull="true" />
      <Column Name="UnitsInStock" Type="System.Int16" DbType="SmallInt" IsReadOnly="true" CanBeNull="true" />
      <Column Name="UnitsOnOrder" Type="System.Int16" DbType="SmallInt" IsReadOnly="true" CanBeNull="true" />
      <Column Name="ReorderLevel" Type="System.Int16" DbType="SmallInt" IsReadOnly="true" CanBeNull="true" />
      <Column Name="Discontinued" Type="System.Boolean" DbType="Bit NOT NULL" IsReadOnly="true" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MinUnitPriceByCategory" Method="MinUnitPriceByCategory" IsComposable="true">
    <Parameter Name="categoryID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Decimal" />
  </Function>
  <Function Name="dbo.TotalProductUnitPriceByCategory" Method="TotalProductUnitPriceByCategory" IsComposable="true">
    <Parameter Name="categoryID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Decimal" />
  </Function>
  <Function Name="dbo.[Whole Or Partial Customers Set]" Method="Whole_Or_Partial_Customers_Set">
    <Parameter Name="param1" Type="System.Int32" DbType="Int" />
    <ElementType Name="Whole_Or_Partial_Customers_SetResult">
      <Column Name="CustomerID" Type="System.String" DbType="NChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="ContactName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ContactTitle" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[Customers Count By Region]" Method="Customers_Count_By_Region">
    <Parameter Name="param1" Type="System.String" DbType="NVarChar(15)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[Get Customer And Orders]" Method="Get_Customer_And_Orders">
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.String" DbType="NChar(5)" />
    <ElementType Name="Get_Customer_And_OrdersResult">
      <Column Name="CustomerID" Type="System.String" DbType="NChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="ContactName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ContactTitle" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[Get Customer And Orders]" Method="Get_Customer_And_Orders1">
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.String" DbType="NChar(5)" />
    <ElementType Name="Get_Customer_And_OrdersResult1">
      <Column Name="CustomerID" Type="System.String" DbType="NChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="ContactName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ContactTitle" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CustOrderHist" Method="CustOrderHist">
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.String" DbType="NChar(5)" />
    <ElementType Name="CustOrderHistResult">
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CustOrderTotal" Method="CustOrderTotal">
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.String" DbType="NChar(5)" />
    <Parameter Name="TotalSales" Parameter="totalSales" Type="System.Decimal" DbType="Money" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>