//// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
//// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
//// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
//// PARTICULAR PURPOSE.
////
//// Copyright (c) Microsoft Corporation. All rights reserved

var myData = new WinJS.Binding.List([
    { title: "The Smoothest", text: "Maybe the smoothest ice cream ever." },
    { title: "What a great flavor!", text: "Although the texture was a bit lacking, this one has the best flavor I have tasted!" },
    { title: "Didn't like the 'choco bits'", text: "The little bits of chocolate just weren't working for me." },
    { title: "Loved the peanut butter", text: "The peanut butter! I loved this ice cream. Did I mention I loved this ice cream! However, The little bits of chocolate just weren't working for me. I will try it again another time to give my final opinion. I will write back when I have finished the next carton." }, 
    { title: "Wish there was more sugar", text: "This wasn't sweet enough for me. I will have to try your other flavors, but maybe this is too healthy for me. Who knows?" }, 
    { title: "Texture was perfect", text: "This was the smoothest ice cream I have ever had" },
    { title: "Kept wishing there was more", text: "When I got to the end of each carton I kept wishing there was more ice cream. It was delicious! The best part of this delicious snack was the strawberries!" },
    { title: "The Smoothest", text: "Maybe the smoothest ice cream ever." },
    { title: "What a great flavor!", text: "Although the texture was a bit lacking, this one has the best flavor I have tasted!" },
    { title: "Didn't like the 'choco bits'", text: "The little bits of chocolate just weren't working for me." },
    { title: "Loved the peanut butter", text: "The peanut butter! I loved this ice cream. Did I mention I loved this ice cream! However, The little bits of chocolate just weren't working for me. I will try it again another time to give my final opinion. I will write back when I have finished the next carton." }, 
    { title: "Wish there was more sugar", text: "This wasn't sweet enough for me. I will have to try your other flavors, but maybe this is too healthy for me. Who knows?" }, 
    { title: "Texture was perfect", text: "This was the smoothest ice cream I have ever had" },
    { title: "Kept wishing there was more", text: "When I got to the end of each carton I kept wishing there was more ice cream. It was delicious! The best part of this delicious snack was the strawberries!" },
    { title: "The Smoothest", text: "Maybe the smoothest ice cream ever." },
    { title: "What a great flavor!", text: "Although the texture was a bit lacking, this one has the best flavor I have tasted!" },
    { title: "Didn't like the 'choco bits'", text: "The little bits of chocolate just weren't working for me." },
    { title: "Loved the peanut butter", text: "The peanut butter! I loved this ice cream. Did I mention I loved this ice cream! However, The little bits of chocolate just weren't working for me. I will try it again another time to give my final opinion. I will write back when I have finished the next carton." }, 
    { title: "Wish there was more sugar", text: "This wasn't sweet enough for me. I will have to try your other flavors, but maybe this is too healthy for me. Who knows?" }, 
    { title: "Texture was perfect", text: "This was the smoothest ice cream I have ever had" },
    { title: "Kept wishing there was more", text: "When I got to the end of each carton I kept wishing there was more ice cream. It was delicious! The best part of this delicious snack was the strawberries!" },
    { title: "The Smoothest", text: "Maybe the smoothest ice cream ever." },
    { title: "What a great flavor!", text: "Although the texture was a bit lacking, this one has the best flavor I have tasted!" },
    { title: "Didn't like the 'choco bits'", text: "The little bits of chocolate just weren't working for me." },
    { title: "Loved the peanut butter", text: "The peanut butter! I loved this ice cream. Did I mention I loved this ice cream! However, The little bits of chocolate just weren't working for me. I will try it again another time to give my final opinion. I will write back when I have finished the next carton." }, 
    { title: "Wish there was more sugar", text: "This wasn't sweet enough for me. I will have to try your other flavors, but maybe this is too healthy for me. Who knows?" }, 
    { title: "Texture was perfect", text: "This was the smoothest ice cream I have ever had" },
    { title: "Kept wishing there was more", text: "When I got to the end of each carton I kept wishing there was more ice cream. It was delicious! The best part of this delicious snack was the strawberries!" },
    { title: "The Smoothest", text: "Maybe the smoothest ice cream ever." },
    { title: "What a great flavor!", text: "Although the texture was a bit lacking, this one has the best flavor I have tasted!" },
    { title: "Didn't like the 'choco bits'", text: "The little bits of chocolate just weren't working for me." },
    { title: "Loved the peanut butter", text: "The peanut butter! I loved this ice cream. Did I mention I loved this ice cream! However, The little bits of chocolate just weren't working for me. I will try it again another time to give my final opinion. I will write back when I have finished the next carton." }, 
    { title: "Wish there was more sugar", text: "This wasn't sweet enough for me. I will have to try your other flavors, but maybe this is too healthy for me. Who knows?" }, 
    { title: "Texture was perfect", text: "This was the smoothest ice cream I have ever had" },
    { title: "Kept wishing there was more", text: "When I got to the end of each carton I kept wishing there was more ice cream. It was delicious! The best part of this delicious snack was the strawberries!" },
    { title: "The Smoothest", text: "Maybe the smoothest ice cream ever." },
    { title: "What a great flavor!", text: "Although the texture was a bit lacking, this one has the best flavor I have tasted!" },
    { title: "Didn't like the 'choco bits'", text: "The little bits of chocolate just weren't working for me." },
    { title: "Loved the peanut butter", text: "The peanut butter! I loved this ice cream. Did I mention I loved this ice cream! However, The little bits of chocolate just weren't working for me. I will try it again another time to give my final opinion. I will write back when I have finished the next carton." }, 
    { title: "Wish there was more sugar", text: "This wasn't sweet enough for me. I will have to try your other flavors, but maybe this is too healthy for me. Who knows?" }, 
    { title: "Texture was perfect", text: "This was the smoothest ice cream I have ever had" },
    { title: "Kept wishing there was more", text: "When I got to the end of each carton I kept wishing there was more ice cream. It was delicious! The best part of this delicious snack was the strawberries!" },
    { title: "The Smoothest", text: "Maybe the smoothest ice cream ever." },
    { title: "What a great flavor!", text: "Although the texture was a bit lacking, this one has the best flavor I have tasted!" },
    { title: "Didn't like the 'choco bits'", text: "The little bits of chocolate just weren't working for me." },
    { title: "Loved the peanut butter", text: "The peanut butter! I loved this ice cream. Did I mention I loved this ice cream! However, The little bits of chocolate just weren't working for me. I will try it again another time to give my final opinion. I will write back when I have finished the next carton." }, 
    { title: "Wish there was more sugar", text: "This wasn't sweet enough for me. I will have to try your other flavors, but maybe this is too healthy for me. Who knows?" }, 
    { title: "Texture was perfect", text: "This was the smoothest ice cream I have ever had" },
    { title: "Kept wishing there was more", text: "When I got to the end of each carton I kept wishing there was more ice cream. It was delicious! The best part of this delicious snack was the strawberries!" },
    { title: "The Smoothest", text: "Maybe the smoothest ice cream ever." },
    { title: "What a great flavor!", text: "Although the texture was a bit lacking, this one has the best flavor I have tasted!" },
    { title: "Didn't like the 'choco bits'", text: "The little bits of chocolate just weren't working for me." },
    { title: "Loved the peanut butter", text: "The peanut butter! I loved this ice cream. Did I mention I loved this ice cream! However, The little bits of chocolate just weren't working for me. I will try it again another time to give my final opinion. I will write back when I have finished the next carton." }, 
    { title: "Wish there was more sugar", text: "This wasn't sweet enough for me. I will have to try your other flavors, but maybe this is too healthy for me. Who knows?" }, 
    { title: "Texture was perfect", text: "This was the smoothest ice cream I have ever had" },
    { title: "Kept wishing there was more", text: "When I got to the end of each carton I kept wishing there was more ice cream. It was delicious! The best part of this delicious snack was the strawberries!" },
    { title: "The Smoothest", text: "Maybe the smoothest ice cream ever." },
    { title: "What a great flavor!", text: "Although the texture was a bit lacking, this one has the best flavor I have tasted!" },
    { title: "Didn't like the 'choco bits'", text: "The little bits of chocolate just weren't working for me." },
    { title: "Loved the peanut butter", text: "The peanut butter! I loved this ice cream. Did I mention I loved this ice cream! However, The little bits of chocolate just weren't working for me. I will try it again another time to give my final opinion. I will write back when I have finished the next carton." }, 
    { title: "Wish there was more sugar", text: "This wasn't sweet enough for me. I will have to try your other flavors, but maybe this is too healthy for me. Who knows?" }, 
    { title: "Texture was perfect", text: "This was the smoothest ice cream I have ever had" },
    { title: "Kept wishing there was more", text: "When I got to the end of each carton I kept wishing there was more ice cream. It was delicious! The best part of this delicious snack was the strawberries!" },
    { title: "The Smoothest", text: "Maybe the smoothest ice cream ever." },
    { title: "What a great flavor!", text: "Although the texture was a bit lacking, this one has the best flavor I have tasted!" },
    { title: "Didn't like the 'choco bits'", text: "The little bits of chocolate just weren't working for me." },
    { title: "Loved the peanut butter", text: "The peanut butter! I loved this ice cream. Did I mention I loved this ice cream! However, The little bits of chocolate just weren't working for me. I will try it again another time to give my final opinion. I will write back when I have finished the next carton." }, 
    { title: "Wish there was more sugar", text: "This wasn't sweet enough for me. I will have to try your other flavors, but maybe this is too healthy for me. Who knows?" }, 
    { title: "Texture was perfect", text: "This was the smoothest ice cream I have ever had" },
    { title: "Kept wishing there was more", text: "When I got to the end of each carton I kept wishing there was more ice cream. It was delicious! The best part of this delicious snack was the strawberries!" },
    { title: "The Smoothest", text: "Maybe the smoothest ice cream ever." },
    { title: "What a great flavor!", text: "Although the texture was a bit lacking, this one has the best flavor I have tasted!" },
    { title: "Didn't like the 'choco bits'", text: "The little bits of chocolate just weren't working for me." },
    { title: "Loved the peanut butter", text: "The peanut butter! I loved this ice cream. Did I mention I loved this ice cream! However, The little bits of chocolate just weren't working for me. I will try it again another time to give my final opinion. I will write back when I have finished the next carton." }, 
    { title: "Wish there was more sugar", text: "This wasn't sweet enough for me. I will have to try your other flavors, but maybe this is too healthy for me. Who knows?" }, 
    { title: "Texture was perfect", text: "This was the smoothest ice cream I have ever had" },
    { title: "Kept wishing there was more", text: "When I got to the end of each carton I kept wishing there was more ice cream. It was delicious! The best part of this delicious snack was the strawberries!" },
    { title: "The Smoothest", text: "Maybe the smoothest ice cream ever." },
    { title: "What a great flavor!", text: "Although the texture was a bit lacking, this one has the best flavor I have tasted!" },
    { title: "Didn't like the 'choco bits'", text: "The little bits of chocolate just weren't working for me." },
    { title: "Loved the peanut butter", text: "The peanut butter! I loved this ice cream. Did I mention I loved this ice cream! However, The little bits of chocolate just weren't working for me. I will try it again another time to give my final opinion. I will write back when I have finished the next carton." }, 
    { title: "Wish there was more sugar", text: "This wasn't sweet enough for me. I will have to try your other flavors, but maybe this is too healthy for me. Who knows?" }, 
    { title: "Texture was perfect", text: "This was the smoothest ice cream I have ever had" },
    { title: "Kept wishing there was more", text: "When I got to the end of each carton I kept wishing there was more ice cream. It was delicious! The best part of this delicious snack was the strawberries!" }
]);
