'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace CalculatorServiceClient
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="CalculatorServiceClient.IServiceCalculate", CallbackContract:=GetType(CalculatorServiceClient.IServiceCalculateCallback), SessionMode:=System.ServiceModel.SessionMode.Required)>  _
    Public Interface IServiceCalculate
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceCalculate/SumByInputValue", ReplyAction:="http://tempuri.org/IServiceCalculate/SumByInputValueResponse")>  _
        Sub SumByInputValue(ByVal dbeOneParameter As Double, ByVal dbeTwoParameter As Double, ByVal strSymbol As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceCalculate/SumByInputValue", ReplyAction:="http://tempuri.org/IServiceCalculate/SumByInputValueResponse")>  _
        Function SumByInputValueAsync(ByVal dbeOneParameter As Double, ByVal dbeTwoParameter As Double, ByVal strSymbol As String) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://tempuri.org/IServiceCalculate/SumByInputValueOneway")>  _
        Sub SumByInputValueOneway(ByVal dbeOneParameter As Double, ByVal dbeTwoParameter As Double, ByVal strSymbol As String)
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://tempuri.org/IServiceCalculate/SumByInputValueOneway")>  _
        Function SumByInputValueOnewayAsync(ByVal dbeOneParameter As Double, ByVal dbeTwoParameter As Double, ByVal strSymbol As String) As System.Threading.Tasks.Task
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IServiceCalculateCallback
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceCalculate/DisplayResultByOption", ReplyAction:="http://tempuri.org/IServiceCalculate/DisplayResultByOptionResponse")>  _
        Sub DisplayResultByOption(ByVal strSymbol As String, ByVal dbeSumValue As Double)
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://tempuri.org/IServiceCalculate/DisPlayResultByOptionOneWay")>  _
        Sub DisPlayResultByOptionOneWay(ByVal strSymbol As String, ByVal dbeSumValue As Double)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IServiceCalculateChannel
        Inherits CalculatorServiceClient.IServiceCalculate, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceCalculateClient
        Inherits System.ServiceModel.DuplexClientBase(Of CalculatorServiceClient.IServiceCalculate)
        Implements CalculatorServiceClient.IServiceCalculate
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext)
            MyBase.New(callbackInstance)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal endpointConfigurationName As String)
            MyBase.New(callbackInstance, endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(callbackInstance, endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(callbackInstance, endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(callbackInstance, binding, remoteAddress)
        End Sub
        
        Public Sub SumByInputValue(ByVal dbeOneParameter As Double, ByVal dbeTwoParameter As Double, ByVal strSymbol As String) Implements CalculatorServiceClient.IServiceCalculate.SumByInputValue
            MyBase.Channel.SumByInputValue(dbeOneParameter, dbeTwoParameter, strSymbol)
        End Sub
        
        Public Function SumByInputValueAsync(ByVal dbeOneParameter As Double, ByVal dbeTwoParameter As Double, ByVal strSymbol As String) As System.Threading.Tasks.Task Implements CalculatorServiceClient.IServiceCalculate.SumByInputValueAsync
            Return MyBase.Channel.SumByInputValueAsync(dbeOneParameter, dbeTwoParameter, strSymbol)
        End Function
        
        Public Sub SumByInputValueOneway(ByVal dbeOneParameter As Double, ByVal dbeTwoParameter As Double, ByVal strSymbol As String) Implements CalculatorServiceClient.IServiceCalculate.SumByInputValueOneway
            MyBase.Channel.SumByInputValueOneway(dbeOneParameter, dbeTwoParameter, strSymbol)
        End Sub
        
        Public Function SumByInputValueOnewayAsync(ByVal dbeOneParameter As Double, ByVal dbeTwoParameter As Double, ByVal strSymbol As String) As System.Threading.Tasks.Task Implements CalculatorServiceClient.IServiceCalculate.SumByInputValueOnewayAsync
            Return MyBase.Channel.SumByInputValueOnewayAsync(dbeOneParameter, dbeTwoParameter, strSymbol)
        End Function
    End Class
End Namespace
