import "Windows.Media.idl";

#include <sdkddkver.h>

namespace MPEG1Source
{
	[version(NTDDI_WIN8)]
    runtimeclass MPEG1ByteStreamHandler
    {
		[default] interface Windows.Media.IMediaExtension;
    }
}