import "wudfddi.idl";

[
    uuid(4871FB77-3CAE-483D-AB5A-6DCD170138BB),
    version(1.0),
    helpstring("Windows SideShow Basic Driver 1.0 Type Library")
]
library AuxDriverLib
{
    importlib("stdole2.tlb");
    [
        uuid(073E9649-9D95-45C6-8AE1-06D112E97914),
        helpstring("WSSBasicDisplayDriver Class")
    ]
    coclass WSSDisplayDriver
    {
        [default] interface IDriverEntry;
    };
};
