/***************************************************************************

Copyright (c) Microsoft Corporation. All rights reserved.
THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.

***************************************************************************/
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21111.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.20207.0.
// 
namespace Microsoft.VsTemplateDesigner {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.20207.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/developer/vstemplate/2005", IsNullable=false)]
    public partial class VSTemplate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VSTemplateTemplateData templateDataField;
        
        private VSTemplateTemplateContent templateContentField;
        
        private VSTemplateWizardExtension[] wizardExtensionField;
        
        private VSTemplateWizardData[] wizardDataField;
        
        private string typeField;
        
        private string versionField;
        
        /// <remarks/>
        public VSTemplateTemplateData TemplateData {
            get {
                return this.templateDataField;
            }
            set {
                this.templateDataField = value;
                this.RaisePropertyChanged("TemplateData");
            }
        }
        
        /// <remarks/>
        public VSTemplateTemplateContent TemplateContent {
            get {
                return this.templateContentField;
            }
            set {
                this.templateContentField = value;
                this.RaisePropertyChanged("TemplateContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WizardExtension")]
        public VSTemplateWizardExtension[] WizardExtension {
            get {
                return this.wizardExtensionField;
            }
            set {
                this.wizardExtensionField = value;
                this.RaisePropertyChanged("WizardExtension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WizardData")]
        public VSTemplateWizardData[] WizardData {
            get {
                return this.wizardDataField;
            }
            set {
                this.wizardDataField = value;
                this.RaisePropertyChanged("WizardData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.20207.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class VSTemplateTemplateData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private NameDescriptionIcon nameField;
        
        private NameDescriptionIcon descriptionField;
        
        private NameDescriptionIcon iconField;
        
        private string previewImageField;
        
        private string projectTypeField;
        
        private string projectSubTypeField;
        
        private string templateIDField;
        
        private string templateGroupIDField;
        
        private string sortOrderField;
        
        private bool createNewFolderField;
        
        private bool createNewFolderFieldSpecified;
        
        private string defaultNameField;
        
        private bool provideDefaultNameField;
        
        private bool provideDefaultNameFieldSpecified;
        
        private bool promptForSaveOnCreationField;
        
        private bool promptForSaveOnCreationFieldSpecified;
        
        private bool enableLocationBrowseButtonField;
        
        private bool enableLocationBrowseButtonFieldSpecified;
        
        private bool enableEditOfLocationFieldField;
        
        private bool enableEditOfLocationFieldFieldSpecified;
        
        private bool hiddenField;
        
        private bool hiddenFieldSpecified;
        
        private string locationFieldMRUPrefixField;
        
        private string numberOfParentCategoriesToRollUpField;
        
        private object createInPlaceField;
        
        private object buildOnLoadField;
        
        private object showByDefaultField;
        
        private VSTemplateTemplateDataLocationField locationFieldField;
        
        private bool locationFieldFieldSpecified;
        
        private bool supportsMasterPageField;
        
        private bool supportsMasterPageFieldSpecified;
        
        private bool supportsCodeSeparationField;
        
        private bool supportsCodeSeparationFieldSpecified;
        
        private bool supportsLanguageDropDownField;
        
        private bool supportsLanguageDropDownFieldSpecified;
        
        private VSTemplateTemplateDataRequiredFrameworkVersion requiredFrameworkVersionField;
        
        private bool requiredFrameworkVersionFieldSpecified;
        
        private string frameworkVersionField;
        
        private VSTemplateTemplateDataMaxFrameworkVersion maxFrameworkVersionField;
        
        private bool maxFrameworkVersionFieldSpecified;
        
        private string customDataSignatureField;
        
        /// <remarks/>
        public NameDescriptionIcon Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        public NameDescriptionIcon Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        public NameDescriptionIcon Icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
                this.RaisePropertyChanged("Icon");
            }
        }
        
        /// <remarks/>
        public string PreviewImage {
            get {
                return this.previewImageField;
            }
            set {
                this.previewImageField = value;
                this.RaisePropertyChanged("PreviewImage");
            }
        }
        
        /// <remarks/>
        public string ProjectType {
            get {
                return this.projectTypeField;
            }
            set {
                this.projectTypeField = value;
                this.RaisePropertyChanged("ProjectType");
            }
        }
        
        /// <remarks/>
        public string ProjectSubType {
            get {
                return this.projectSubTypeField;
            }
            set {
                this.projectSubTypeField = value;
                this.RaisePropertyChanged("ProjectSubType");
            }
        }
        
        /// <remarks/>
        public string TemplateID {
            get {
                return this.templateIDField;
            }
            set {
                this.templateIDField = value;
                this.RaisePropertyChanged("TemplateID");
            }
        }
        
        /// <remarks/>
        public string TemplateGroupID {
            get {
                return this.templateGroupIDField;
            }
            set {
                this.templateGroupIDField = value;
                this.RaisePropertyChanged("TemplateGroupID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string SortOrder {
            get {
                return this.sortOrderField;
            }
            set {
                this.sortOrderField = value;
                this.RaisePropertyChanged("SortOrder");
            }
        }
        
        /// <remarks/>
        public bool CreateNewFolder {
            get {
                return this.createNewFolderField;
            }
            set {
                this.createNewFolderField = value;
                this.RaisePropertyChanged("CreateNewFolder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreateNewFolderSpecified {
            get {
                return this.createNewFolderFieldSpecified;
            }
            set {
                this.createNewFolderFieldSpecified = value;
                this.RaisePropertyChanged("CreateNewFolderSpecified");
            }
        }
        
        /// <remarks/>
        public string DefaultName {
            get {
                return this.defaultNameField;
            }
            set {
                this.defaultNameField = value;
                this.RaisePropertyChanged("DefaultName");
            }
        }
        
        /// <remarks/>
        public bool ProvideDefaultName {
            get {
                return this.provideDefaultNameField;
            }
            set {
                this.provideDefaultNameField = value;
                this.RaisePropertyChanged("ProvideDefaultName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProvideDefaultNameSpecified {
            get {
                return this.provideDefaultNameFieldSpecified;
            }
            set {
                this.provideDefaultNameFieldSpecified = value;
                this.RaisePropertyChanged("ProvideDefaultNameSpecified");
            }
        }
        
        /// <remarks/>
        public bool PromptForSaveOnCreation {
            get {
                return this.promptForSaveOnCreationField;
            }
            set {
                this.promptForSaveOnCreationField = value;
                this.RaisePropertyChanged("PromptForSaveOnCreation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PromptForSaveOnCreationSpecified {
            get {
                return this.promptForSaveOnCreationFieldSpecified;
            }
            set {
                this.promptForSaveOnCreationFieldSpecified = value;
                this.RaisePropertyChanged("PromptForSaveOnCreationSpecified");
            }
        }
        
        /// <remarks/>
        public bool EnableLocationBrowseButton {
            get {
                return this.enableLocationBrowseButtonField;
            }
            set {
                this.enableLocationBrowseButtonField = value;
                this.RaisePropertyChanged("EnableLocationBrowseButton");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnableLocationBrowseButtonSpecified {
            get {
                return this.enableLocationBrowseButtonFieldSpecified;
            }
            set {
                this.enableLocationBrowseButtonFieldSpecified = value;
                this.RaisePropertyChanged("EnableLocationBrowseButtonSpecified");
            }
        }
        
        /// <remarks/>
        public bool EnableEditOfLocationField {
            get {
                return this.enableEditOfLocationFieldField;
            }
            set {
                this.enableEditOfLocationFieldField = value;
                this.RaisePropertyChanged("EnableEditOfLocationField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnableEditOfLocationFieldSpecified {
            get {
                return this.enableEditOfLocationFieldFieldSpecified;
            }
            set {
                this.enableEditOfLocationFieldFieldSpecified = value;
                this.RaisePropertyChanged("EnableEditOfLocationFieldSpecified");
            }
        }
        
        /// <remarks/>
        public bool Hidden {
            get {
                return this.hiddenField;
            }
            set {
                this.hiddenField = value;
                this.RaisePropertyChanged("Hidden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HiddenSpecified {
            get {
                return this.hiddenFieldSpecified;
            }
            set {
                this.hiddenFieldSpecified = value;
                this.RaisePropertyChanged("HiddenSpecified");
            }
        }
        
        /// <remarks/>
        public string LocationFieldMRUPrefix {
            get {
                return this.locationFieldMRUPrefixField;
            }
            set {
                this.locationFieldMRUPrefixField = value;
                this.RaisePropertyChanged("LocationFieldMRUPrefix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string NumberOfParentCategoriesToRollUp {
            get {
                return this.numberOfParentCategoriesToRollUpField;
            }
            set {
                this.numberOfParentCategoriesToRollUpField = value;
                this.RaisePropertyChanged("NumberOfParentCategoriesToRollUp");
            }
        }
        
        /// <remarks/>
        public object CreateInPlace {
            get {
                return this.createInPlaceField;
            }
            set {
                this.createInPlaceField = value;
                this.RaisePropertyChanged("CreateInPlace");
            }
        }
        
        /// <remarks/>
        public object BuildOnLoad {
            get {
                return this.buildOnLoadField;
            }
            set {
                this.buildOnLoadField = value;
                this.RaisePropertyChanged("BuildOnLoad");
            }
        }
        
        /// <remarks/>
        public object ShowByDefault {
            get {
                return this.showByDefaultField;
            }
            set {
                this.showByDefaultField = value;
                this.RaisePropertyChanged("ShowByDefault");
            }
        }
        
        /// <remarks/>
        public VSTemplateTemplateDataLocationField LocationField {
            get {
                return this.locationFieldField;
            }
            set {
                this.locationFieldField = value;
                this.RaisePropertyChanged("LocationField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LocationFieldSpecified {
            get {
                return this.locationFieldFieldSpecified;
            }
            set {
                this.locationFieldFieldSpecified = value;
                this.RaisePropertyChanged("LocationFieldSpecified");
            }
        }
        
        /// <remarks/>
        public bool SupportsMasterPage {
            get {
                return this.supportsMasterPageField;
            }
            set {
                this.supportsMasterPageField = value;
                this.RaisePropertyChanged("SupportsMasterPage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SupportsMasterPageSpecified {
            get {
                return this.supportsMasterPageFieldSpecified;
            }
            set {
                this.supportsMasterPageFieldSpecified = value;
                this.RaisePropertyChanged("SupportsMasterPageSpecified");
            }
        }
        
        /// <remarks/>
        public bool SupportsCodeSeparation {
            get {
                return this.supportsCodeSeparationField;
            }
            set {
                this.supportsCodeSeparationField = value;
                this.RaisePropertyChanged("SupportsCodeSeparation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SupportsCodeSeparationSpecified {
            get {
                return this.supportsCodeSeparationFieldSpecified;
            }
            set {
                this.supportsCodeSeparationFieldSpecified = value;
                this.RaisePropertyChanged("SupportsCodeSeparationSpecified");
            }
        }
        
        /// <remarks/>
        public bool SupportsLanguageDropDown {
            get {
                return this.supportsLanguageDropDownField;
            }
            set {
                this.supportsLanguageDropDownField = value;
                this.RaisePropertyChanged("SupportsLanguageDropDown");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SupportsLanguageDropDownSpecified {
            get {
                return this.supportsLanguageDropDownFieldSpecified;
            }
            set {
                this.supportsLanguageDropDownFieldSpecified = value;
                this.RaisePropertyChanged("SupportsLanguageDropDownSpecified");
            }
        }
        
        /// <remarks/>
        public VSTemplateTemplateDataRequiredFrameworkVersion RequiredFrameworkVersion {
            get {
                return this.requiredFrameworkVersionField;
            }
            set {
                this.requiredFrameworkVersionField = value;
                this.RaisePropertyChanged("RequiredFrameworkVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RequiredFrameworkVersionSpecified {
            get {
                return this.requiredFrameworkVersionFieldSpecified;
            }
            set {
                this.requiredFrameworkVersionFieldSpecified = value;
                this.RaisePropertyChanged("RequiredFrameworkVersionSpecified");
            }
        }
        
        /// <remarks/>
        public string FrameworkVersion {
            get {
                return this.frameworkVersionField;
            }
            set {
                this.frameworkVersionField = value;
                this.RaisePropertyChanged("FrameworkVersion");
            }
        }
        
        /// <remarks/>
        public VSTemplateTemplateDataMaxFrameworkVersion MaxFrameworkVersion {
            get {
                return this.maxFrameworkVersionField;
            }
            set {
                this.maxFrameworkVersionField = value;
                this.RaisePropertyChanged("MaxFrameworkVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxFrameworkVersionSpecified {
            get {
                return this.maxFrameworkVersionFieldSpecified;
            }
            set {
                this.maxFrameworkVersionFieldSpecified = value;
                this.RaisePropertyChanged("MaxFrameworkVersionSpecified");
            }
        }
        
        /// <remarks/>
        public string CustomDataSignature {
            get {
                return this.customDataSignatureField;
            }
            set {
                this.customDataSignatureField = value;
                this.RaisePropertyChanged("CustomDataSignature");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.20207.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class NameDescriptionIcon : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string packageField;
        
        private string idField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Package {
            get {
                return this.packageField;
            }
            set {
                this.packageField = value;
                this.RaisePropertyChanged("Package");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.20207.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    public enum VSTemplateTemplateDataLocationField {
        
        /// <remarks/>
        Enabled,
        
        /// <remarks/>
        Disabled,
        
        /// <remarks/>
        Hidden,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.20207.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    public enum VSTemplateTemplateDataRequiredFrameworkVersion {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2.0")]
        Item20,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3.0")]
        Item30,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3.5")]
        Item35,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4.0")]
        Item40,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.20207.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    public enum VSTemplateTemplateDataMaxFrameworkVersion {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2.0")]
        Item20,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3.0")]
        Item30,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3.5")]
        Item35,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4.0")]
        Item40,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.20207.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class VSTemplateTemplateContent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        private VSTemplateTemplateContentCustomParameter[] customParametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Project", typeof(VSTemplateTemplateContentProject))]
        [System.Xml.Serialization.XmlElementAttribute("ProjectCollection", typeof(VSTemplateTemplateContentProjectCollection))]
        [System.Xml.Serialization.XmlElementAttribute("ProjectItem", typeof(VSTemplateTemplateContentProjectItem))]
        [System.Xml.Serialization.XmlElementAttribute("References", typeof(VSTemplateTemplateContentReferences))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CustomParameter", IsNullable=false)]
        public VSTemplateTemplateContentCustomParameter[] CustomParameters {
            get {
                return this.customParametersField;
            }
            set {
                this.customParametersField = value;
                this.RaisePropertyChanged("CustomParameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.20207.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class VSTemplateTemplateContentProject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        private string fileField;
        
        private string targetFileNameField;
        
        private bool replaceParametersField;
        
        private bool replaceParametersFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Folder", typeof(Folder))]
        [System.Xml.Serialization.XmlElementAttribute("ProjectItem", typeof(ProjectItem))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string File {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
                this.RaisePropertyChanged("File");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TargetFileName {
            get {
                return this.targetFileNameField;
            }
            set {
                this.targetFileNameField = value;
                this.RaisePropertyChanged("TargetFileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ReplaceParameters {
            get {
                return this.replaceParametersField;
            }
            set {
                this.replaceParametersField = value;
                this.RaisePropertyChanged("ReplaceParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReplaceParametersSpecified {
            get {
                return this.replaceParametersFieldSpecified;
            }
            set {
                this.replaceParametersFieldSpecified = value;
                this.RaisePropertyChanged("ReplaceParametersSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.20207.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/developer/vstemplate/2005", IsNullable=false)]
    public partial class Folder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        private string nameField;
        
        private string targetFolderNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Folder", typeof(Folder))]
        [System.Xml.Serialization.XmlElementAttribute("ProjectItem", typeof(ProjectItem))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TargetFolderName {
            get {
                return this.targetFolderNameField;
            }
            set {
                this.targetFolderNameField = value;
                this.RaisePropertyChanged("TargetFolderName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.20207.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/developer/vstemplate/2005", IsNullable=false)]
    public partial class ProjectItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string targetFileNameField;
        
        private bool replaceParametersField;
        
        private bool replaceParametersFieldSpecified;
        
        private bool openInEditorField;
        
        private bool openInEditorFieldSpecified;
        
        private int openOrderField;
        
        private bool openOrderFieldSpecified;
        
        private bool openInWebBrowserField;
        
        private bool openInWebBrowserFieldSpecified;
        
        private bool openInHelpBrowserField;
        
        private bool openInHelpBrowserFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TargetFileName {
            get {
                return this.targetFileNameField;
            }
            set {
                this.targetFileNameField = value;
                this.RaisePropertyChanged("TargetFileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ReplaceParameters {
            get {
                return this.replaceParametersField;
            }
            set {
                this.replaceParametersField = value;
                this.RaisePropertyChanged("ReplaceParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReplaceParametersSpecified {
            get {
                return this.replaceParametersFieldSpecified;
            }
            set {
                this.replaceParametersFieldSpecified = value;
                this.RaisePropertyChanged("ReplaceParametersSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool OpenInEditor {
            get {
                return this.openInEditorField;
            }
            set {
                this.openInEditorField = value;
                this.RaisePropertyChanged("OpenInEditor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OpenInEditorSpecified {
            get {
                return this.openInEditorFieldSpecified;
            }
            set {
                this.openInEditorFieldSpecified = value;
                this.RaisePropertyChanged("OpenInEditorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int OpenOrder {
            get {
                return this.openOrderField;
            }
            set {
                this.openOrderField = value;
                this.RaisePropertyChanged("OpenOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OpenOrderSpecified {
            get {
                return this.openOrderFieldSpecified;
            }
            set {
                this.openOrderFieldSpecified = value;
                this.RaisePropertyChanged("OpenOrderSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool OpenInWebBrowser {
            get {
                return this.openInWebBrowserField;
            }
            set {
                this.openInWebBrowserField = value;
                this.RaisePropertyChanged("OpenInWebBrowser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OpenInWebBrowserSpecified {
            get {
                return this.openInWebBrowserFieldSpecified;
            }
            set {
                this.openInWebBrowserFieldSpecified = value;
                this.RaisePropertyChanged("OpenInWebBrowserSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool OpenInHelpBrowser {
            get {
                return this.openInHelpBrowserField;
            }
            set {
                this.openInHelpBrowserField = value;
                this.RaisePropertyChanged("OpenInHelpBrowser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OpenInHelpBrowserSpecified {
            get {
                return this.openInHelpBrowserFieldSpecified;
            }
            set {
                this.openInHelpBrowserFieldSpecified = value;
                this.RaisePropertyChanged("OpenInHelpBrowserSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.20207.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class VSTemplateTemplateContentProjectCollection : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProjectTemplateLink", typeof(ProjectTemplateLink))]
        [System.Xml.Serialization.XmlElementAttribute("SolutionFolder", typeof(SolutionFolder))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.20207.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/developer/vstemplate/2005", IsNullable=false)]
    public partial class ProjectTemplateLink : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string projectNameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProjectName {
            get {
                return this.projectNameField;
            }
            set {
                this.projectNameField = value;
                this.RaisePropertyChanged("ProjectName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.20207.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/developer/vstemplate/2005", IsNullable=false)]
    public partial class SolutionFolder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProjectTemplateLink", typeof(ProjectTemplateLink))]
        [System.Xml.Serialization.XmlElementAttribute("SolutionFolder", typeof(SolutionFolder))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.20207.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class VSTemplateTemplateContentProjectItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string subTypeField;
        
        private string customToolField;
        
        private string itemTypeField;
        
        private bool replaceParametersField;
        
        private bool replaceParametersFieldSpecified;
        
        private string targetFileNameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubType {
            get {
                return this.subTypeField;
            }
            set {
                this.subTypeField = value;
                this.RaisePropertyChanged("SubType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CustomTool {
            get {
                return this.customToolField;
            }
            set {
                this.customToolField = value;
                this.RaisePropertyChanged("CustomTool");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemType {
            get {
                return this.itemTypeField;
            }
            set {
                this.itemTypeField = value;
                this.RaisePropertyChanged("ItemType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ReplaceParameters {
            get {
                return this.replaceParametersField;
            }
            set {
                this.replaceParametersField = value;
                this.RaisePropertyChanged("ReplaceParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReplaceParametersSpecified {
            get {
                return this.replaceParametersFieldSpecified;
            }
            set {
                this.replaceParametersFieldSpecified = value;
                this.RaisePropertyChanged("ReplaceParametersSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TargetFileName {
            get {
                return this.targetFileNameField;
            }
            set {
                this.targetFileNameField = value;
                this.RaisePropertyChanged("TargetFileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.20207.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class VSTemplateTemplateContentReferences : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VSTemplateTemplateContentReferencesReference referenceField;
        
        /// <remarks/>
        public VSTemplateTemplateContentReferencesReference Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
                this.RaisePropertyChanged("Reference");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.20207.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class VSTemplateTemplateContentReferencesReference : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string assemblyField;
        
        /// <remarks/>
        public string Assembly {
            get {
                return this.assemblyField;
            }
            set {
                this.assemblyField = value;
                this.RaisePropertyChanged("Assembly");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.20207.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class VSTemplateTemplateContentCustomParameter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.20207.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class VSTemplateWizardExtension : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] assemblyField;
        
        private object[] fullClassNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Assembly")]
        public object[] Assembly {
            get {
                return this.assemblyField;
            }
            set {
                this.assemblyField = value;
                this.RaisePropertyChanged("Assembly");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FullClassName")]
        public object[] FullClassName {
            get {
                return this.fullClassNameField;
            }
            set {
                this.fullClassNameField = value;
                this.RaisePropertyChanged("FullClassName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.20207.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class VSTemplateWizardData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
