// ATLExeCOMServer.idl : IDL source for ATLExeCOMServer
//

// This file will be processed by the MIDL tool to
// produce the type library (ATLExeCOMServer.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(47E764FE-D065-4BDE-8943-30F46664B02C),
	dual,
	nonextensible,
	helpstring("ISimpleObject Interface"),
	pointer_default(unique)
]
interface ISimpleObject : IDispatch{
	[propget, id(1), helpstring("property FloatProperty")] HRESULT FloatProperty([out, retval] FLOAT* pVal);
	[propput, id(1), helpstring("property FloatProperty")] HRESULT FloatProperty([in] FLOAT newVal);
	[id(2), helpstring("method HelloWorld")] HRESULT HelloWorld([out,retval] BSTR* pRet);
	[id(3), helpstring("method GetProcessThreadID")] HRESULT GetProcessThreadID([out] LONG* pdwProcessId, [out] LONG* pdwThreadId);
};
[
	uuid(C7902493-E23D-4487-824F-4AB97BD8B86D),
	version(1.0),
	helpstring("ATLExeCOMServer 1.0 Type Library")
]
library ATLExeCOMServerLib
{
	importlib("stdole2.tlb");
	[
		uuid(6EE998B7-61C8-4D54-B27A-F623E8C1EA64),
		helpstring("_ISimpleObjectEvents Interface")
	]
	dispinterface _ISimpleObjectEvents
	{
		properties:
		methods:
			[id(1), helpstring("method FloatPropertyChanging")] void FloatPropertyChanging([in] FLOAT NewValue, [in,out] VARIANT_BOOL* Cancel);
	};
	[
		uuid(9465BE08-C9FA-4DDF-A56E-57B92BCDEEB0),
		helpstring("SimpleObject Class")
	]
	coclass SimpleObject
	{
		[default] interface ISimpleObject;
		[default, source] dispinterface _ISimpleObjectEvents;
	};
};
