//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://WCF_SharePointCallingService", ConfigurationName="ISharePointItemInserter")]
public interface ISharePointItemInserter
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://WCF_SharePointCallingService/ISharePointItemInserter/InsertItem", ReplyAction="http://WCF_SharePointCallingService/ISharePointItemInserter/InsertItemResponse")]
    bool InsertItem(string Title, string Body);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ISharePointItemInserterChannel : ISharePointItemInserter, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SharePointItemInserterClient : System.ServiceModel.ClientBase<ISharePointItemInserter>, ISharePointItemInserter
{
    
    public SharePointItemInserterClient()
    {
    }
    
    public SharePointItemInserterClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SharePointItemInserterClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SharePointItemInserterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SharePointItemInserterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool InsertItem(string Title, string Body)
    {
        return base.Channel.InsertItem(Title, Body);
    }
}
