//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSWMIEnableDisableNetworkAdapter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSWMIEnableDisableNetworkAdapter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string BtnText_Disable {
            get {
                return ResourceManager.GetString("BtnText_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string BtnText_Enable {
            get {
                return ResourceManager.GetString("BtnText_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not be enable because of Error:.
        /// </summary>
        internal static string CanNotEnableMsg {
            get {
                return ResourceManager.GetString("CanNotEnableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgDisabledNetworkAdapter {
            get {
                object obj = ResourceManager.GetObject("ImgDisabledNetworkAdapter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgEnabledNetworkAdapter {
            get {
                object obj = ResourceManager.GetObject("ImgEnabledNetworkAdapter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to run this sample as Administrator!.
        /// </summary>
        internal static string MsgElevatedRequire {
            get {
                return ResourceManager.GetString("MsgElevatedRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string NetConnectionStatus0 {
            get {
                return ResourceManager.GetString("NetConnectionStatus0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        internal static string NetConnectionStatus1 {
            get {
                return ResourceManager.GetString("NetConnectionStatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed.
        /// </summary>
        internal static string NetConnectionStatus10 {
            get {
                return ResourceManager.GetString("NetConnectionStatus10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid address.
        /// </summary>
        internal static string NetConnectionStatus11 {
            get {
                return ResourceManager.GetString("NetConnectionStatus11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials required.
        /// </summary>
        internal static string NetConnectionStatus12 {
            get {
                return ResourceManager.GetString("NetConnectionStatus12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string NetConnectionStatus2 {
            get {
                return ResourceManager.GetString("NetConnectionStatus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting.
        /// </summary>
        internal static string NetConnectionStatus3 {
            get {
                return ResourceManager.GetString("NetConnectionStatus3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware not present.
        /// </summary>
        internal static string NetConnectionStatus4 {
            get {
                return ResourceManager.GetString("NetConnectionStatus4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware disabled.
        /// </summary>
        internal static string NetConnectionStatus5 {
            get {
                return ResourceManager.GetString("NetConnectionStatus5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware malfunction.
        /// </summary>
        internal static string NetConnectionStatus6 {
            get {
                return ResourceManager.GetString("NetConnectionStatus6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media disconnected.
        /// </summary>
        internal static string NetConnectionStatus7 {
            get {
                return ResourceManager.GetString("NetConnectionStatus7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating.
        /// </summary>
        internal static string NetConnectionStatus8 {
            get {
                return ResourceManager.GetString("NetConnectionStatus8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication succeeded.
        /// </summary>
        internal static string NetConnectionStatus9 {
            get {
                return ResourceManager.GetString("NetConnectionStatus9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft All-In-One Code Framework.
        /// </summary>
        internal static string OneCodeCaption {
            get {
                return ResourceManager.GetString("OneCodeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is being disabled. Please wait for seconds..
        /// </summary>
        internal static string ProgressTextDisableEnd {
            get {
                return ResourceManager.GetString("ProgressTextDisableEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is being enabled. Please wait for seconds..
        /// </summary>
        internal static string ProgressTextEnableEnd {
            get {
                return ResourceManager.GetString("ProgressTextEnableEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Adapter: .
        /// </summary>
        internal static string StatusTextBegin {
            get {
                return ResourceManager.GetString("StatusTextBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was failed to disable!.
        /// </summary>
        internal static string StatusTextFailDisableEnd {
            get {
                return ResourceManager.GetString("StatusTextFailDisableEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was failed to enable!.
        /// </summary>
        internal static string StatusTextFailEnableEnd {
            get {
                return ResourceManager.GetString("StatusTextFailEnableEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Adapters Count: .
        /// </summary>
        internal static string StatusTextInitial {
            get {
                return ResourceManager.GetString("StatusTextInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been disabled  successfully!.
        /// </summary>
        internal static string StatusTextSuccessDisableEnd {
            get {
                return ResourceManager.GetString("StatusTextSuccessDisableEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been enabled  successfully!.
        /// </summary>
        internal static string StatusTextSuccessEnableEnd {
            get {
                return ResourceManager.GetString("StatusTextSuccessEnableEnd", resourceCulture);
            }
        }
    }
}
