//-----------------------------------------------------------------------
// <copyright file="Request.idl" company="Microsoft">
//  Copyright (c) Microsoft Corporation. All rights reserved.
// </copyright>
//
// Module:
//      SpbAccelerometer.idl
//
// Description:
//      This is the interface definition file for the SpbAccerleromter 
//      Library.  It provides a interfaces and objects to assist in 
//      Sensor UMDF driver developement.
//
//-----------------------------------------------------------------------

import "wudfddi.idl";
import "sensordevice.idl";

[
    uuid(1C267C0C-38BD-485E-BA8A-DC0281A23E7F),
    version(1.0),
    helpstring("SPB Accelerometer Driver Type Library")
]
library SpbAccelerometerDriverLib
{
    importlib("stdole2.tlb");
    [
        uuid(182BBB15-88C0-4E9C-A16F-EB5CDBC226C8),
        helpstring("SpbAccelerometerDriver Class")
    ]
    coclass SpbAccelerometerDriver
    {
        [default] interface IDriverEntry;
    };
};