/*++
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
//
// Copyright (c) Microsoft Corporation. All rights reserved
//
// Module:
    SensorsHIDClassDriver.idl
//      
//
// Description:
//  HID sensor class driver

--*/

import "wudfddi.idl";

[
    uuid(464f4632-7cb6-4a94-87ad-feaf558ffb48
),
    version(1.0),
    helpstring("HID Sensor Driver Sample Type Library")
]
library SensorsHIDDriverSampleLib
{
    importlib("stdole2.tlb");
    [
        uuid(a65a2b1f-b99b-40f4-9fc3-7e76ffb21bcf
),
        helpstring("SensorsHIDDriverSample Class")
    ]
    coclass SensorsHIDDriverSample
    {
        [default] interface IDriverEntry;
    };
};
