// TestAddin2.idl : IDL source for TestAddin2
//

// This file will be processed by the MIDL tool to
// produce the type library (TestAddin2.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(CE895442-9981-4315-AA85-4B9A5C7739D8),
	dual,
	nonextensible,
	helpstring("IRibbonCallback Interface"),
	pointer_default(unique)
]
interface IRibbonCallback : IDispatch{
	[id(42),helpstring("Button Callback")]
	HRESULT ButtonClicked([in]IDispatch* ribbonControl);
};
[
	object,
	uuid(0B80B66C-58B7-434B-AE44-790EAE625514),
	dual,
	nonextensible,
	helpstring("IConnect Interface"),
	pointer_default(unique)
]
interface IConnect : IDispatch{
};
[
	uuid(0C94B6BE-7D35-46DC-92D1-D6FD5187ECF2),
	version(1.0),
	helpstring("TestAddin2 1.0 Type Library")
]
library TestAddin2Lib
{
	importlib("stdole2.tlb");
	[
		uuid(D7A48F42-CB48-4BB9-867C-7CEE387FB22A),
		helpstring("Connect Class")
	]
	coclass Connect
	{
		[default] interface IRibbonCallback;
	};
};
