// ATLDllCOMServer.idl : IDL source for ATLDllCOMServer
//

// This file will be processed by the MIDL tool to
// produce the type library (ATLDllCOMServer.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(830F85D0-91B9-406D-A273-BC33133DD44B),
	dual,
	nonextensible,
	helpstring("ISimpleObject Interface"),
	pointer_default(unique)
]
interface ISimpleObject : IDispatch{
	[propget, id(1), helpstring("property FloatProperty")] HRESULT FloatProperty([out, retval] FLOAT* pVal);
	[propput, id(1), helpstring("property FloatProperty")] HRESULT FloatProperty([in] FLOAT newVal);
	[id(2), helpstring("method HelloWorld")] HRESULT HelloWorld([out,retval] BSTR* pRet);
	[id(3), helpstring("method GetProcessThreadID")] HRESULT GetProcessThreadID([out] LONG* pdwProcessId, [out] LONG* pdwThreadId);
};
[
	uuid(9B23EFED-A0C1-46B6-A903-218206447F3E),
	version(1.0),
	helpstring("ATLDllCOMServer 1.0 Type Library")
]
library ATLDllCOMServerLib
{
	importlib("stdole2.tlb");
	[
		uuid(87AD6FBC-8735-407C-9758-C80B48C78E7C),
		helpstring("_ISimpleObjectEvents Interface")
	]
	dispinterface _ISimpleObjectEvents
	{
		properties:
		methods:
			[id(1), helpstring("method FloatPropertyChanging")] void FloatPropertyChanging([in] FLOAT NewValue, [in,out] VARIANT_BOOL* Cancel);
	};
	[
		uuid(92FCF37F-F6C7-4F8A-AA09-1A14BA118084),
		helpstring("SimpleObject Class")
	]
	coclass SimpleObject
	{
		[default] interface ISimpleObject;
		[default, source] dispinterface _ISimpleObjectEvents;
	};
};
