// MenuAndCommands.idl : IDL source for MenuAndCommands.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (MenuAndCommands.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
midl_pragma warning (disable : 2015)
import "vsshell.idl";
midl_pragma warning (default : 2015)

//standard dispids
#define DISPID_Name                     (-800)
#define DISPID_Delete                   (-801)
#define DISPID_Object                   (-802)
#define DISPID_Parent                   (-803)
#define DISPID_NewEnum					(-4)
#define DISPID_Value					(0)

[
	uuid(d2e01e35-0c79-41ff-a181-93018becd16e),
	version(1.0),
	helpstring("MenuAndCommands 1.0 Type Library")
]
library MenuAndCommandsLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");


	[
		uuid(ab7eeef6-3221-4aef-b91c-240b508d9c5a),
		helpstring("MenuAndCommands Package")
	]
	coclass MenuAndCommandsPackage
	{
		[default] interface IVsPackage;
	};
};
