#define IDS_SERVERNOTIFICATION 100
#define IDS_UNKNOWNDATAFORMAT  101
#define IDS_PRINTERDELETED     102
#define IDS_UNREGISTER         103
#define IDS_STARTDOC           104
#define IDS_ENDDOC             105
#define IDS_ENDDIALOG          106

