//******************************************************************
//
// Copyright (c) Microsoft Corporation. All rights reserved.
// This code is licensed under the Visual Studio SDK license terms.
// THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
// IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
// PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
//
//******************************************************************
using Microsoft.VisualStudio.TextTemplating.VSHost;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using VSShell = global::Microsoft.VisualStudio.Shell;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslModeling = global::Microsoft.VisualStudio.Modeling;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Linq;
using System.Windows.Forms;
	
namespace Company.SlideShowDesigner
{
	/// <summary>
	/// This class implements the VS package that integrates this DSL into Visual Studio.
	/// </summary>
	[VSShell::DefaultRegistryRoot("Software\\Microsoft\\VisualStudio\\11.0")]
	[VSShell::PackageRegistration(RegisterUsing = VSShell::RegistrationMethod.Assembly, UseManagedResourcesOnly = true)]
	[VSShell::ProvideToolWindow(typeof(SlideShowDesignerExplorerToolWindow), MultiInstances = false, Style = VSShell::VsDockStyle.Tabbed, Orientation = VSShell::ToolWindowOrientation.Right, Window = "{3AE79031-E1BC-11D0-8F78-00A0C9110057}")]
	[VSShell::ProvideToolWindowVisibility(typeof(SlideShowDesignerExplorerToolWindow), Constants.SlideShowDesignerEditorFactoryId)]
	[VSShell::ProvideStaticToolboxGroup("@SlideShowDesignerToolboxTab;Company.SlideShowDesigner.Dsl.dll", "Company.SlideShowDesigner.SlideShowDesignerToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("Company.SlideShowDesigner.SlideShowDesignerToolboxTab",
					"@PhotoToolboxItem;Company.SlideShowDesigner.Dsl.dll", 
					"Company.SlideShowDesigner.PhotoToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"CreateExampleClassF1Keyword", 
					"@PhotoToolboxBitmap;Company.SlideShowDesigner.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("Company.SlideShowDesigner.SlideShowDesignerToolboxTab",
					"@TransitionToolboxItem;Company.SlideShowDesigner.Dsl.dll", 
					"Company.SlideShowDesigner.TransitionToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ConnectExampleRelationF1Keyword", 
					"@TransitionToolboxBitmap;Company.SlideShowDesigner.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideEditorFactory(typeof(SlideShowDesignerEditorFactory), 103, TrustLevel = VSShellInterop::__VSEDITORTRUSTLEVEL.ETL_AlwaysTrusted)]
	[VSShell::ProvideEditorExtension(typeof(SlideShowDesignerEditorFactory), "." + Constants.DesignerFileExtension, 50)]
	[VSShell::ProvideEditorLogicalView(typeof(SlideShowDesignerEditorFactory), "{7651A702-06E5-11D1-8EBD-00A0C90F26EA}")] // Designer logical view GUID i.e. VSConstants.LOGVIEWID_Designer
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.CSharpProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.VisualBasicProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::RegisterAsDslToolsEditor]
	[global::System.Runtime.InteropServices.ComVisible(true)]
	[DslShell::ProvideBindingPath]
	[DslShell::ProvideXmlEditorChooserBlockSxSWithXmlEditor(@"SlideShowDesigner", typeof(SlideShowDesignerEditorFactory))]

	internal abstract partial class SlideShowDesignerPackageBase : DslShell::ModelingPackage
	{
		protected global::Company.SlideShowDesigner.SlideShowDesignerToolboxHelper toolboxHelper;	
		
		/// <summary>
		/// Initialization method called by the package base class when this package is loaded.
		/// </summary>
		protected override void Initialize()
		{
			base.Initialize();

			// Register the editor factory used to create the DSL editor.
			this.RegisterEditorFactory(new SlideShowDesignerEditorFactory(this));
			
			// Initialize the toolbox helper
			toolboxHelper = new global::Company.SlideShowDesigner.SlideShowDesignerToolboxHelper(this);

			// Create the command set that handles menu commands provided by this package.
			SlideShowDesignerCommandSet commandSet = new SlideShowDesignerCommandSet(this);
			commandSet.Initialize();
			
			// Create the command set that handles cut/copy/paste commands provided by this package.
			SlideShowDesignerClipboardCommandSet clipboardCommandSet = new SlideShowDesignerClipboardCommandSet(this);
			clipboardCommandSet.Initialize();
			
			// Register the model explorer tool window for this DSL.
			this.AddToolWindow(typeof(SlideShowDesignerExplorerToolWindow));

			// Initialize Extension Registars
			// this is a partial method call
			this.InitializeExtensions();

			// Add dynamic toolbox items
			this.SetupDynamicToolbox();
		}

		/// <summary>
		/// Partial method to initialize ExtensionRegistrars (if any) in the DslPackage
		/// </summary>
		partial void InitializeExtensions();
		
		/// <summary>
		/// Returns any dynamic tool items for the designer
		/// </summary>
		/// <remarks>The default implementation is to return the list of items from the generated toolbox helper.</remarks>
		protected override global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			try
			{
				Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
				return toolboxHelper.CreateToolboxItems();
			}
			catch(global::System.Exception e)
			{
				global::System.Diagnostics.Debug.Fail("Exception thrown during toolbox item creation.  This may result in Package Load Failure:\r\n\r\n" + e);
				throw;
			}
		}
		
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		protected override object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
		
			// Retrieve the specified ToolboxItem from the DSL
			return toolboxHelper.GetToolboxItemData(itemId, format);
		}
	}

}

//
// Package attributes which may need to change are placed on the partial class below, rather than in the main include file.
//
namespace Company.SlideShowDesigner
{
    /// <summary>
    /// Double-derived class to allow easier code customization.
    /// </summary>
    /// <remarks>
    /// A package load key is required to allow this package to load when the Visual Studio SDK is not installed.
    /// Package load keys may be obtained from http://msdn.microsoft.com/vstudio/extend.
    /// Consult the Visual Studio SDK documentation for more information.
    /// [VSShell::ProvideLoadKey("Standard", Constants.ProductVersion, Constants.ProductName, Constants.CompanyName, 1)]
    /// </remarks>
    [VSShell::ProvideMenuResource("1000.ctmenu", 1)]
    [VSShell::ProvideToolboxItems(1)]
    // Temporarily (for 2010 beta 2) use a a local copy of the ProvideDirectiveProcessor attribute to work around bugs in the attribute and CreatePkgDef.exe
    [ProvideDirectiveProcessor(typeof(global::Company.SlideShowDesigner.SlideShowDesignerDirectiveProcessor), global::Company.SlideShowDesigner.SlideShowDesignerDirectiveProcessor.SlideShowDesignerDirectiveProcessorName, "A directive processor that provides access to SlideShowDesigner files")]
    //[VSTextTemplatingHost::ProvideDirectiveProcessor(typeof(global::Company.SlideShowDesigner.SlideShowDesignerDirectiveProcessor), global::Company.SlideShowDesigner.SlideShowDesignerDirectiveProcessor.SlideShowDesignerDirectiveProcessorName, "A directive processor that provides access to SlideShowDesigner files")]
    [global::System.Runtime.InteropServices.Guid(Constants.SlideShowDesignerPackageId)]
    internal sealed partial class SlideShowDesignerPackage : SlideShowDesignerPackageBase
    {
    }
}