//-----------------------------------------------------------------------
// <copyright file="Request.idl" company="Microsoft">
//  Copyright (c) Microsoft Corporation. All rights reserved.
// </copyright>
//
// Module:
//      Request.idl
//
// Description:
//      This is the interface definition file for the Request Library.  
//      It provides a interfaces and objects
//      to assist in Sensor UMDF driver developement.
//
//-----------------------------------------------------------------------

cpp_quote("#if (_WIN32_WINNT >= 0x0600) // Windows Vista and later")

import "propidl.idl";
import "oaidl.idl";
import "wudfddi.idl";

// Forward declaration
interface IRequestCallback;

[
    object,
    uuid(a6f40424-c961-4c80-85da-4ea2fcb231ad),
    helpstring("IRequest Interface"),
    pointer_default(unique)
]
interface IRequest : IUnknown
{
    HRESULT Initialize(
        [in]  IWDFDevice*        pWdfDevice,
        [in]  PCWSTR             pszTargetPath
        );

    HRESULT CreateAndSendWrite(
        [in]  BYTE*  pInBuffer,
        [in]  SIZE_T inBufferSize
        );

    HRESULT CreateAndSendWriteReadSequence(
        [in]  BYTE*  pInBuffer,
        [in]  SIZE_T inBufferSize,
        [out] BYTE*  pOutBuffer,
        [in]  SIZE_T outBufferSize,
        [in]  ULONG  delayInUs
        );

    HRESULT Cancel(
        );
};

[
    uuid(92c6b13f-aa9e-4caf-95ed-90b4deac3a94),
    version(1.0),
    helpstring("SPB Request Type Library")
]
library SpbRequestLibrary
{
    importlib("stdole2.tlb");
    [
        uuid(2285a47a-ea72-4f79-a041-40aa4a5cd87d),
        helpstring("SPB Request Class")
    ]
    coclass SpbRequest
    {
        [default] interface IRequest;
    };
};

cpp_quote("#endif // (_WIN32_WINNT >= 0x0600)")