/*++

Copyright (c) Microsoft Corporation.  All rights reserved.

    THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
    KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
    PURPOSE.

Module Name:

    WpdBluetoothGattServiceDriver.idl
    
Abstract:

--*/


import "oaidl.idl";
import "ocidl.idl";

import "wudfddi.idl";

[
    uuid(74FF6859-73D1-488C-B2EA-88BD6DA31A17),
    version(1.0),
    helpstring("Bluetooth GATT WPD Services Sample Driver Type Library")
]
library WpdBluetoothGattServiceSampleDriverLib
{
    importlib("stdole2.tlb");
    [
        uuid(CFC0AF02-CE72-4717-83E7-D51BCFCBE87B),
        helpstring("WpdBluetoothGattServiceSampleDriver Class")
    ]
    coclass WpdBluetoothGattServiceSampleDriver
    {
        [default] interface IDriverEntry;
    };
};


