'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ISharePointAnnouncementAdder")>  _
Public Interface ISharePointAnnouncementAdder
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISharePointAnnouncementAdder/AddAnnouncement", ReplyAction:="http://tempuri.org/ISharePointAnnouncementAdder/AddAnnouncementResponse")>  _
    Function AddAnnouncement(ByVal Title As String, ByVal Body As String) As Boolean
End Interface

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
Public Interface ISharePointAnnouncementAdderChannel
    Inherits ISharePointAnnouncementAdder, System.ServiceModel.IClientChannel
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
Partial Public Class SharePointAnnouncementAdderClient
    Inherits System.ServiceModel.ClientBase(Of ISharePointAnnouncementAdder)
    Implements ISharePointAnnouncementAdder
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String)
        MyBase.New(endpointConfigurationName)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(binding, remoteAddress)
    End Sub
    
    Public Function AddAnnouncement(ByVal Title As String, ByVal Body As String) As Boolean Implements ISharePointAnnouncementAdder.AddAnnouncement
        Return MyBase.Channel.AddAnnouncement(Title, Body)
    End Function
End Class
